var MSG = {
    id_events : "events",
    id_motion : "moves",
    id_control : "control",
    id_acousto_optic : "show",
    id_sensors : "sensors",
    id_math : "math",
    id_variable : "variable",
    id_function : "functions",
    id_start : "start",
    id_when_start : "click 'Run' to start",
    id_go_to_start : "go to start",
    id_motion_speed : "speed",
    id_motion_continued : "duration",
    id_motion_angle : "angle",
    id_motion_distance : "reflectance",
    id_motion_second : "s",
    id_motion_degree : "degree",
    id_motion_step : "steps",
    id_motion_execution : "execute action",
    id_motion_stop : "stop action",
    id_motion_myaction : "my actions",
    id_motion_time : "duration",
    id_motion_millisecond : "ms",
    id_motion_go_forward : "forward",
    id_motion_go_back : "backward",
    id_motion_go_left : "turn left",
    id_motion_go_right : "turn right",
    id_motion_speed_normal : "middle",
    id_motion_speed_fast : "fast",
    id_motion_speed_faster : "very fast",
    id_motion_speed_slow : "slow",
    id_motion_speed_slower : "very slow",
    id_motion_steer_gear : "servo",
    id_motion_turn_angle : "rotate",
    id_motion_turn_rotation : "rotate",
    id_motion_turn_clockwise : "clockwise",
    id_motion_turn_unclockwise : "anti-clockwise",
    id_while : "while",
    id_repeat : "repeat",
    id_control_wait : "wait",
    id_control_repeat : "repeat",
    id_control_wait_for : "wait until",
    id_control_repeat_times : "times",
    id_until : "until",
    id_control_seconds : "ms",
    id_control_execution : "run to",
    id_control_then : "then",
    id_control_infinite_loop : "repeat execution",
    id_acousto_play_tone : "play tune",
    id_acousto_beat : "tempo",
    id_acousto_play_sound : "play effect",
    id_acousto_mysound : "my voice",
    id_acousto_stop_play : "stop playback",
    id_acousto_lights_on : "light up",
    id_acousto_color : "colour",
    id_acousto_continued : "duration",
    id_acousto_second : "s",
    id_acousto_left : "left lamp",
    id_acousto_right : "right lamp",
    id_acousto_eyes_lights : "eye lamp",
    id_acousto_brightness : "brightness",
    id_acousto_bgMusic : "background music",
    id_acousto_bgLight : "background lighting",
    id_acousto_emotions : "expression",
    id_acousto_scenelight : "light display",
    id_acousto_custom : "custom light",
    id_acousto_r : "red",
    id_acousto_g : "green",
    id_acousto_b : "blue",
    id_acousto_times : "times",
    id_all_lightup : "all bright",
    id_self_defined : "custom",
    id_events_when : "when",
    id_events_clicked : "is tapped",
    id_events_when_device : "when the phone/tablet",
    id_events_when_front_obstacle : "when there are obstacles in front",
    id_events_when_obstacle : "when the IR sensor",
    id_events_cm : "cm",
    event_click : "tap",
    event_start : "start",
    id_events_move_right : "move right",
    id_events_move_left : "move left",
    id_events_move_up : "move up",
    id_events_move_down : "move down",
    id_events_move_forward : "move forward",
    id_events_move_back : "move backward",
    ahead_obstacle : "obstacles in front",
    obstacle_distance : "distance to obstacle",
    phone_pad : "phone/tablet",
    tilt_right : "tilt right",
    tilt_left : "tilt left",
    tilt_up : "tilt up",
    tilt_down : "tilt down",
    tilt_swing : "tilt swing",
    id_sensor_IR_sensor : "IR sensor",
    id_sensor_reflectance_between_obstacle : "distance from obstacle",
    id_sensor_device : "phone/tablet",
    low_power : "low power",
    create_variable : "new variable",
    rename_variable : "rename variable",
    variable1 : "variable 1",
    variable_take : "set",
    variable_set_to : "as",
    variable_value : "the value of",
    variable_placeholder : "Please enter the variable name",
    increase : "increase",
    reduce : "decrease",
    id_math_and : "and",
    id_math_or : "or",
    id_math_not : "not",
    define_function : "define function",
    rename_function : "Rename function",
    beat_2 : "2",
    beat_1 : "1",
    beat_2_1 : "1/2",
    beat_4_1 : "1/4",
    beat_8_1 : "1/8",
    id_all : "all",
    animal : "animal",
    machine : "machine",
    recording : "recording",
    bear : "bear",
    bird : "bird",
    chicken : "chicken",
    cow : "cow",
    dog : "dog",
    elephant : "elephant",
    giraffe : "giraffe",
    horse : "horse",
    lion : "lion",
    monkey : "monkey",
    pig : "pig",
    rhinoceros : "rhinoceros",
    sealions : "sealions",
    tiger : "tiger",
    walrus : "walrus",
    ambulance : "ambulance",
    busy_tone : "busy tone",
    carhorn : "carhorn",
    carhorn1 : "carhorn1",
    doorbell : "doorbell",
    engine : "engine",
    laser : "laser",
    meebot : "meebot",
    police_car_1 : "police_car_1",
    police_car_2 : "police_car_2",
    ringtones : "ringtones",
    robot : "robot",
    telephone_call : "telephone Call",
    touch_tone : "touch Tone",
    wave : "wave",
    id_happy : "happy",
    id_jingya : "surprised",
    id_relei : "tears",
    id_leiguang : "flashing tears",
    id_shangxin : "sad",
    id_yun : "dizzy",
    id_cry : "cry",
    id_fadai : "dazed",
    id_zhayan : "blink",
    id_haixiu : "shy",
    id_shanshuo : "flash",
    id_huxi : "breath",
    id_fengshan : "fan",
    id_yugua : "wipers",
    id_repet_error_hint : "Name already saved.",
    id_deng : "7colored lights",
    id_disco : "disco",
    id_caise : "color stacking",
    id_sanyuanse : "primary colors",
    command : "command",
    emotion : "emotion",
    cheer : "cheer",
    transfiguration : "transform",
    happy : "happy",
    yawn : "yawn",
    snoring : "snoring",
    surprise : "surprise",
    actingcute : "cute",
    angry : "angry",
    fail : "failure",
    lose : "lost",
    received : "receive",
    complete : "complete",
    cover : "shield",
    move : "move",
    doubt : "doubt",
    nonsense : "raving",
    emotion_engine : "engine",
    cheerful : "cheerful",
    support : "support",
    yes : "yes",
    come_and_play : "song 1",
    flexin : "song 2",
    london_bridge : "song 3",
    yankee_doodle : "song 4",
    variable_inputrule_msg : "Cannot begin with a digit. Special characters cannot be entered. A maximum of %1 characters or %2 Chinese characters can be entered.",
    recording_placeholder : "Please enter a recording name",
    sysVoiceName : "my voice",
    sysActionName : "my action",
    posture_named_popup_placeholder : "action",
    recording_name_repea : "Sorry, the recording name you entered has been used",
    save_fail : "Failed to save sound effect",
    not_file : "Recording file does not exist",
    error_param : "Parameter error",
    sys_sound_name : "system sound effects",
    has_no_record_authority : "Current device does not have access to recordings",
    porject_alert_content_02 : "Error in base service operation. The error message",
    project_has_no_change : "The current program has not changed",
    newProjectName : "my project",
    add_project_pop_title : "project name",
    add_project_placeholder : "project name",
    porject_alert_content_01 : "Item name already exists. Please enter again.",
    porject_alert_content_06 : "Project saved",
    porject_alert_content_10 : "Please slide left to delete 1 action and then add a new one.",
    porject_alert_content_11 : "Please slide left to delete 1 recording and then add a new one.",
    porject_alert_content_04 : "Failed to read project",
    porject_alert_content_05 : "Sorry, the program block in the read item file contains errors.",
    close_blue : "Bluetooth is connected, it does disconnect?",
    cancel_btn : "cancel",
    sure_btn : "OK",
    id_sensor_gyroscope : "gyroscope",
    x_axie : "roll angle",
    y_axie : "pitch angle",
    z_axie : "heading angle",
    id_sensor : "IR sensor",
    current_block_disabled : "Current program block not available",
    id_copy_instruction : "copy command",
    id_copy_current : "copy current",
    id_copy_current_all : "current and lower",
    motion_placeholder : "my actions",
    sys_motion_name : "system actions",
    motion_name_repea : "Sorry, the current action name has been used!",
    return : "Back",
    exit_popup_title : "tips",
    exit_tips : "The current program is not saved, whether to continue to exit？",
    version_title : "Blockly version info",
    version_des : "Your have the latest version of Blockly",
    version_btn : "Revert to an earlier version",
    blockly_guide1 : "Tap here to see help and Blockly version info",
    blockly_guide2 : "Tap here to switch to an earlier version of Blockly",
    guide_go : "skip",
    version_msg : "Version update info",
    update_record : "Update history",
    attention : "note",
    sure : "OK",
    record1 : "Optimized Blockly visual programming tool by improving experience and stability.",
    record2 : "Optimized the popup for command parameter settings, with more intuitive command parameter settings.",
    record3 : "Optimized command categories, added several commands, and made them more intuitive and easier to understand.",
    record4 : "New Blockly may not be able to run previous programs! You can revert to an earlier version to run.",
    no_circle_servo_info : "There is currently no wheel mode servo (can rotate 360°). Do you need to set one up?",
    no_common_servo_info : "There is currently no angle mode servo (can rotate within a designated range). Do you need to set one up?",
    no_circle_servo : "Current equipment wheelless steering",
    no_rotate_servo : "Current equipment has no angle mode servo",
    servo_changed_tips : "Servo mode has been changed. Please set the parameters again.",
    edit_cancel : "cancel",
    edit_save : "save",
    edit_delete : "delete",
    id_math_remainder : "remainder",
    id_math_round : "rounding",
    id_math_ceil : "up",
    id_math_floor : "down",
    id_math_integer : "integer",
    id_math_odd : "odd",
    id_math_even : "even",
    id_math_prime : "prime number",
    id_math_positive : "positive number",
    id_math_negative : "negative number",
    release : "Release",
    click : "click",
    db_click : "double click",
    press_hold : "press hold",
    touch_sensor : "touch sensor",
    status : "status is",
    id_sensor_set_gyroscope : "gyroscope",
    id_sensor_angle_to_zero : "angle zero",
    id_sensor_angle : "angle",
    gyroscope : "gyroscope",
    touch_tips : "The touch sensor is not connected to the current model",
    gyroscope_tips : "The gyro sensor is not connected to the current model",
    lights_tips : "The current model is not connected to any light",
    disconnected : "Disconnected",
    current_value : "current value",
    recordTime_too_short : "recording time is too short",
    id_math_is : "is",
    project_unsaved : "Untiled",
    edit_edittemp : "edit",
    name_empty : "name is required",
    reminder_cannot_zero : "divisor can not be 0",
    infrared_tips : "Infrared sensor is not connected to the current model",
    project_not_saved : "don not save",
    var_name_repea : "Sorry, the current variable name has been used!",
    nubmer_cannot_negative : "The number of divisors and divisors can not be negative!",
    yu_cannot_zero : "The remainder cannot be 0!",
    id_motion_turn_stop : "Stop",
    servo : "servo",
    electric_machinery : "motor",
    electric_machinery_rotate : "rotate",
    electric_machinery_rotate_speed : "speed",
    electric_machinery_rotate_speed_minns : "rpm",
    when_ultrasonic_sensor : "when ultrasonic sensor",
    ultrasonic_sensor : "ultrasonic sensor",
    ultrasonic_tips : "Current model unconnected ultrasonic sensor",
    ultrasonic_lights : "ultrasonic lamp",
    infrared_ultrasonic_tips : "The current model is not connected to an IR sensor and ultrasonic sensor",
    guide_step1 : "In the Programming Lab, you can view robot programs",
    guide_step2 : "and program your own robot",
    guide_step3 : "Apply your knowledge from the Training Base to program your Jimu robot!",
    current_has_disabled_block : "Some blocks unavailable in the current program.",
    id_helloworld : "'Hello，world！I am Jimu'",
};