var MSG = {
    id_events : "eventos",
    id_motion : "movimientos",
    id_control : "control",
    id_acousto_optic : "reproducción",
    id_sensors : "sensores",
    id_math : "math",
    id_variable : "variable",
    id_function : "funciones",
    id_start : "iniciar",
    id_when_start : "pulse \"Ejecutar\" para comenzar",
    id_go_to_start : "ve al inicio.",
    id_motion_speed : "velocidad",
    id_motion_continued : "duración",
    id_motion_angle : "ángulo",
    id_motion_distance : "reflectancia",
    id_motion_second : "s",
    id_motion_degree : "grado",
    id_motion_step : "pasos",
    id_motion_execution : "ejecutar acción",
    id_motion_stop : "detener acción",
    id_motion_myaction : "mis acciones",
    id_motion_time : "duración",
    id_motion_millisecond : "ms",
    id_motion_go_forward : "avanzar",
    id_motion_go_back : "retroceder",
    id_motion_go_left : "girar a izqda.",
    id_motion_go_right : "girar a dcha.",
    id_motion_speed_normal : "medio",
    id_motion_speed_fast : "rápido",
    id_motion_speed_faster : "muy rápido",
    id_motion_speed_slow : "lento",
    id_motion_speed_slower : "muy lento",
    id_motion_steer_gear : "servomotor",
    id_motion_turn_angle : "girar",
    id_motion_turn_rotation : "girar",
    id_motion_turn_clockwise : "en sentido horario",
    id_motion_turn_unclockwise : "en sentido contrahorario",
    id_while : "mientras",
    id_repeat : "repetir",
    id_control_wait : "esperar",
    id_control_repeat : "repetir",
    id_control_wait_for : "esperar hasta",
    id_control_repeat_times : "veces",
    id_until : "hasta",
    id_control_seconds : "ms",
    id_control_execution : "ejecutar a",
    id_control_then : "a continuación",
    id_control_infinite_loop : "repetir ejecución",
    id_acousto_play_tone : "reproducir tono",
    id_acousto_beat : "ritmo",
    id_acousto_play_sound : "reproducir efecto",
    id_acousto_mysound : "mi voz",
    id_acousto_stop_play : "detener reprod.",
    id_acousto_lights_on : "iluminar",
    id_acousto_color : "color",
    id_acousto_continued : "duración",
    id_acousto_second : "s",
    id_acousto_left : "lámpara izqda.",
    id_acousto_right : "lámpara dcha.",
    id_acousto_eyes_lights : "lámpara del ojo",
    id_acousto_brightness : "brillo",
    id_acousto_bgMusic : "música de fondo",
    id_acousto_bgLight : "iluminación de fondo",
    id_acousto_emotions : "expresión",
    id_acousto_scenelight : "luz de escena",
    id_acousto_custom : "luz personalizada",
    id_acousto_r : "rojo",
    id_acousto_g : "verde",
    id_acousto_b : "azul",
    id_acousto_times : "veces",
    id_all_lightup : "todo brillante",
    id_self_defined : "personalizar",
    id_events_when : "cuando",
    id_events_clicked : "se toca",
    id_events_when_device : "cuando el teléfono/tableta",
    id_events_when_front_obstacle : "cuando hay obstáculos delante",
    id_events_when_obstacle : "cuando el sensor infrarrojo",
    id_events_cm : "cm",
    event_click : "tocar",
    event_start : "iniciar",
    id_events_move_right : "mover a dcha.",
    id_events_move_left : "mover a izqda.",
    id_events_move_up : "mover arriba",
    id_events_move_down : "mover abajo",
    id_events_move_forward : "avanzar",
    id_events_move_back : "retroceder",
    ahead_obstacle : "obstáculos delante",
    obstacle_distance : "distancia al obstáculo",
    phone_pad : "teléfono/tableta",
    tilt_right : "inclinar a dcha.",
    tilt_left : "inclinar a izqda.",
    tilt_up : "inclinar hacia arriba",
    tilt_down : "inclinar hacia abajo",
    tilt_swing : "inclinar para balancear",
    id_sensor_IR_sensor : "sensor infrarrojo",
    id_sensor_reflectance_between_obstacle : "distancia del obstáculo",
    id_sensor_device : "teléfono/tableta",
    low_power : "batería baja",
    create_variable : "nueva variable",
    rename_variable : "renombrar variable",
    variable1 : "variable 1",
    variable_take : "establecer",
    variable_set_to : "como",
    variable_value : "el valor de",
    variable_placeholder : "Introduce el nombre de la variable",
    increase : "aumentar",
    reduce : "reducir",
    id_math_and : "y",
    id_math_or : "o",
    id_math_not : "no",
    define_function : "definir función",
    rename_function : "Renombrar función",
    beat_2 : "2",
    beat_1 : "1",
    beat_2_1 : "1/2",
    beat_4_1 : "1/4",
    beat_8_1 : "1/8",
    id_all : "todo",
    animal : "animal",
    machine : "máquina",
    recording : "grabación",
    bear : "oso",
    bird : "pájaro",
    chicken : "pollo",
    cow : "vaca",
    dog : "perro",
    elephant : "elefante",
    giraffe : "jirafa",
    horse : "caballo",
    lion : "león",
    monkey : "mono",
    pig : "cerdo",
    rhinoceros : "rinoceronte",
    sealions : "león marino",
    tiger : "tigre",
    walrus : "morsa",
    ambulance : "ambulancia",
    busy_tone : "tono ocupado",
    carhorn : "altavoz de vehículo",
    carhorn1 : "altavoz de vehículo 1",
    doorbell : "timbre",
    engine : "motor",
    laser : "láser",
    meebot : "meebot",
    police_car_1 : "coche de policía 1",
    police_car_2 : "coche de policía 2",
    ringtones : "tonos",
    robot : "robot",
    telephone_call : "llamada telefónica",
    touch_tone : "marcación por tonos",
    wave : "saludar",
    id_happy : "contento",
    id_jingya : "sorprendido",
    id_relei : "lágrimas",
    id_leiguang : "lágrimas luminosas",
    id_shangxin : "triste",
    id_yun : "mareado",
    id_cry : "llorar",
    id_fadai : "aturdido",
    id_zhayan : "guiño",
    id_haixiu : "tímido",
    id_shanshuo : "parpadeo",
    id_huxi : "respiración",
    id_fengshan : "ventilador",
    id_yugua : "limpiaparabrisas",
    id_repet_error_hint : "El nombre ya se ha guardado.",
    id_deng : "indicador LED de 7 colores",
    id_disco : "disco",
    id_caise : "superposición de luces",
    id_sanyuanse : "colores primarios",
    command : "mando",
    emotion : "emoción",
    cheer : "animar",
    transfiguration : "transformar",
    happy : "contento",
    yawn : "bostezo",
    snoring : "ronquidos",
    surprise : "sorpresa",
    actingcute : "linda",
    angry : "enojado",
    fail : "fracaso",
    lose : "perdido",
    received : "recibir",
    complete : "completar",
    cover : "proteger",
    move : "movimiento",
    doubt : "pregunta",
    nonsense : "delirante",
    emotion_engine : "motor",
    cheerful : "alegre",
    support : "apoyo",
    yes : "sí",
    come_and_play : "canción 1",
    flexin : "canción 2",
    london_bridge : "canción 3",
    yankee_doodle : "canción 4",
    variable_inputrule_msg : "No se puede comenzar con un dígito. No se pueden introducir caracteres especiales. Se puede introducir un máximo de %1 caracteres o %2 caracteres chinos.",
    recording_placeholder : "Nombre de grabación",
    sysVoiceName : "voz",
    sysActionName : "nueva acción",
    posture_named_popup_placeholder : "acción",
    recording_name_repea : "El nombre de grabación introducido ya existe",
    save_fail : "Imposible guardar el efecto de sonido",
    not_file : "El archivo de grabación no existe",
    error_param : "Error de parámetro",
    sys_sound_name : "efectos de sonido del sistema",
    has_no_record_authority : "El dispositivo actual no tiene acceso a las grabaciones",
    porject_alert_content_02 : "Se ha producido un error en la operación de servicio base. El mensaje de error",
    project_has_no_change : "El programa actual no ha sido modificado.",
    newProjectName : "nuevo proyecto",
    add_project_pop_title : "nombre de proyecto",
    add_project_placeholder : "nombre de proyecto",
    porject_alert_content_01 : "El nombre del artículo ya existe. Introduzca un nombre de nuevo.",
    porject_alert_content_06 : "Proyecto guardado",
    porject_alert_content_10 : "Deslízate a la izqda. para eliminar 1 acción y añade una nueva.",
    porject_alert_content_11 : "Deslízate a la izqda. para eliminar 1 grabación y añade una nueva.",
    porject_alert_content_04 : "No se ha podido leer el proyecto.",
    porject_alert_content_05 : "El bloque de programa en el archivo de elemento de lectura contiene errores.",
    close_blue : "Conexión Bluetooth activa. ¿Deseas desactivarla?",
    cancel_btn : "cancelar",
    sure_btn : "aceptar",
    id_sensor_gyroscope : "giroscopio",
    x_axie : "ángulo de rotación",
    y_axie : "ángulo de paso",
    z_axie : "ángulo de encabezado",
    id_sensor : "sensor infrarrojo",
    current_block_disabled : "El bloque de programa actual no está disponible",
    id_copy_instruction : "copiar comando",
    id_copy_current : "copiar actual",
    id_copy_current_all : "actual e inferior",
    motion_placeholder : "mis acciones",
    sys_motion_name : "acciones del sistema",
    motion_name_repea : "El nombre de la acción actual ya existe.",
    return : "Atrás",
    exit_popup_title : "consejos",
    exit_tips : "El programa actual no está guardado. ¿Deseas continuar para salir?",
    version_title : "Información de la versión de Blockly",
    version_des : "Tienes la versión de Blockly más reciente",
    version_btn : "Revertir a una versión anterior",
    blockly_guide1 : "Toca aquí para ver la ayuda y la información de la versión de Blockly",
    blockly_guide2 : "Toca aquí para cambiar a una versión anterior de Blockly",
    guide_go : "omitir",
    version_msg : "Información de actualización de versión",
    update_record : "Historial de actualizaciones",
    attention : "nota",
    sure : "aceptar",
    record1 : "Se ha optimizado la herramienta de programación visual de Blockly mediante la mejora de la experiencia y la estabilidad.",
    record2 : "Se ha optimizado el cuadro emergente para la configuración de parámetros de comando con una configuración más intuitiva.",
    record3 : "Se han optimizado las categorías de comando, se han añadido varios comandos y se han hecho más intuitivos y fáciles de entender.",
    record4 : "Es posible que el nuevo Blockly no pueda ejecutar programas anteriores. Puedes revertir a una versión anterior para ejecutarlos.",
    no_circle_servo_info : "Actualmente, no hay ningún servomotor de modo de rueda (capacidad de giro de 360°). ¿Quieres configurar uno?",
    no_common_servo_info : "Actualmente, no hay ningún servomotor de modo de ángulo (capacidad de giro de en un ángulo especificado). ¿Quieres configurar uno?",
    no_circle_servo : "El servomotor del modelo actual no tiene un modo de rotación de 360º.",
    no_rotate_servo : "El equipamiento actual no tiene servomotor de modo de ángulo.",
    servo_changed_tips : "El modo servomotor se ha cambiado. Vuelve a establecer los parámetros.",
    edit_cancel : "cancelar",
    edit_save : "guardar",
    edit_delete : "eliminar",
    id_math_remainder : "recordatorio",
    id_math_round : "redondeo",
    id_math_ceil : "arriba",
    id_math_floor : "abajo",
    id_math_integer : "entero",
    id_math_odd : "número impar",
    id_math_even : "número par",
    id_math_prime : "número primo",
    id_math_positive : "numero positivo",
    id_math_negative : "numero negativo",
    release : "Soltar",
    click : "clic",
    db_click : "doble clic",
    press_hold : "mantener",
    touch_sensor : "sensor táctil",
    status : "el estado es",
    id_sensor_set_gyroscope : "establecer giroscopio",
    id_sensor_angle_to_zero : "todos los ángulos a cero grados",
    id_sensor_angle : "ángulo",
    gyroscope : "giroscopio",
    touch_tips : "El modelo en uso no está conectado a ningún sensor táctil",
    gyroscope_tips : "El modelo en uso no está conectado a ningún sensor giroscopio",
    lights_tips : "El modelo actual no está conectado a la luz.",
    disconnected : "Desconectado",
    current_value : "valor actual",
    recordTime_too_short : "el tiempo de grabación es demasiado corto",
    id_math_is : "es",
    project_unsaved : "No guardado",
    edit_edittemp : "editar",
    name_empty : "el nombre es obligatorio",
    reminder_cannot_zero : "divisor no puede ser 0",
    infrared_tips : "El modelo en uso no está conectado a ningún sensor infrarrojo",
    project_not_saved : "no guardes",
    var_name_repea : "Lo sentimos, el nombre de la variable actual se ha utilizado!",
    nubmer_cannot_negative : "Excedente, dividendo, divisor no puede ser negativo",
    yu_cannot_zero : "El resto no puede ser cero",
    id_motion_turn_stop : "Detener",
    servo : "servomotor",
    electric_machinery : "motor",
    electric_machinery_rotate : "girar",
    electric_machinery_rotate_speed : "velocidad",
    electric_machinery_rotate_speed_minns : "rpm",
    when_ultrasonic_sensor : "cuando el sensor ultrasónico",
    ultrasonic_sensor : "sensor ultrasónico",
    ultrasonic_tips : "El modelo actual no está conectado a ningún sensor ultrasónico",
    ultrasonic_lights : "luz ultrasónica",
    infrared_ultrasonic_tips : "El modelo actual no está conectado a ningún sensor infrarrojo ni sensor ultrasónico",
    guide_step1 : "En el Laboratorio de programación, puedes ver programas de robots",
    guide_step2 : "y programar tu propio robot",
    guide_step3 : "¡Aplica los conocimientos que has obtenido en el Campamento de aprendizaje para programar tu propio robot Jimu!",
    current_has_disabled_block : "Algunos bloques no están disponibles en el programa actual.",
    id_helloworld : "'¡Hola a todos! Soy Jimu.'",
};