var MSG = {
    id_events : "événements",
    id_motion : "mouvements",
    id_control : "contrôler",
    id_acousto_optic : "afficher",
    id_sensors : "capteurs",
    id_math : "math",
    id_variable : "variable",
    id_function : "fonctionnalités",
    id_start : "démarrer",
    id_when_start : "appuyez sur « exécuter » pour démarrer",
    id_go_to_start : "aller sur démarrer",
    id_motion_speed : "vitesse",
    id_motion_continued : "durée",
    id_motion_angle : "angle",
    id_motion_distance : "réflectivité",
    id_motion_second : "s",
    id_motion_degree : "degré",
    id_motion_step : "étapes",
    id_motion_execution : "exécuter action",
    id_motion_stop : "arrêter action",
    id_motion_myaction : "mes actions",
    id_motion_time : "durée",
    id_motion_millisecond : "ms",
    id_motion_go_forward : "avant",
    id_motion_go_back : "arrière",
    id_motion_go_left : "tourner à gauche",
    id_motion_go_right : "tourner à droite",
    id_motion_speed_normal : "au centre",
    id_motion_speed_fast : "rapide",
    id_motion_speed_faster : "très rapide",
    id_motion_speed_slow : "lentement",
    id_motion_speed_slower : "très lentement",
    id_motion_steer_gear : "servo",
    id_motion_turn_angle : "pivoter",
    id_motion_turn_rotation : "pivoter",
    id_motion_turn_clockwise : "sens horaire",
    id_motion_turn_unclockwise : "sens antihoraire",
    id_while : "pendant que",
    id_repeat : "répéter",
    id_control_wait : "attendre",
    id_control_repeat : "répéter",
    id_control_wait_for : "attendre jusqu'à",
    id_control_repeat_times : "fois",
    id_until : "jusqu'à",
    id_control_seconds : "ms",
    id_control_execution : "exécuter",
    id_control_then : "ensuite",
    id_control_infinite_loop : "répéter exécution",
    id_acousto_play_tone : "lecture audio",
    id_acousto_beat : "tempo",
    id_acousto_play_sound : "lecture d'effet",
    id_acousto_mysound : "ma voix",
    id_acousto_stop_play : "arrêter playback",
    id_acousto_lights_on : "allumer",
    id_acousto_color : "couleur",
    id_acousto_continued : "durée",
    id_acousto_second : "secondes",
    id_acousto_left : "lampe gauche",
    id_acousto_right : "lampe droite",
    id_acousto_eyes_lights : "lampe œil",
    id_acousto_brightness : "luminosité",
    id_acousto_bgMusic : "musique de fond",
    id_acousto_bgLight : "éclairage de fond",
    id_acousto_emotions : "expression",
    id_acousto_scenelight : "affichage lumineux",
    id_acousto_custom : "lumière personnalisée",
    id_acousto_r : "rouge",
    id_acousto_g : "vert",
    id_acousto_b : "bleu",
    id_acousto_times : "fois",
    id_all_lightup : "complètement illuminé",
    id_self_defined : "personnalisé",
    id_events_when : "lorsque",
    id_events_clicked : "est tapé",
    id_events_when_device : "lorsque le téléphone/la tablette",
    id_events_when_front_obstacle : "lorsque les obstacles sont devant",
    id_events_when_obstacle : "lorsque le capteur IR",
    id_events_cm : "cm",
    event_click : "taper",
    event_start : "démarrer",
    id_events_move_right : "aller à droite",
    id_events_move_left : "aller à gauche",
    id_events_move_up : "monter",
    id_events_move_down : "descendre",
    id_events_move_forward : "avancer",
    id_events_move_back : "reculer",
    ahead_obstacle : "obstacles devant",
    obstacle_distance : "distance de l'obstacle",
    phone_pad : "téléphone/tablette",
    tilt_right : "incliner à droite",
    tilt_left : "incliner à gauche",
    tilt_up : "incliner vers le haut",
    tilt_down : "incliner vers le bas",
    tilt_swing : "balancer",
    id_sensor_IR_sensor : "capteur infrarouge",
    id_sensor_reflectance_between_obstacle : "distance de l'obstacle",
    id_sensor_device : "téléphone/tablette",
    low_power : "basse puissance",
    create_variable : "nouvelle variable",
    rename_variable : "renommer variable",
    variable1 : "variable 1",
    variable_take : "définir",
    variable_set_to : "comme",
    variable_value : "la valeur de",
    variable_placeholder : "Veuillez saisir le nom de la variable",
    increase : "augmenter",
    reduce : "diminuer",
    id_math_and : "et",
    id_math_or : "ou",
    id_math_not : "non",
    define_function : "définir la fonction",
    rename_function : "Renommer la fonction",
    beat_2 : "2",
    beat_1 : "1",
    beat_2_1 : "1/2",
    beat_4_1 : "1/4",
    beat_8_1 : "1/8",
    id_all : "tout",
    animal : "animal",
    machine : "machine",
    recording : "enregistrement",
    bear : "ours",
    bird : "oiseau",
    chicken : "poulet",
    cow : "vache",
    dog : "chien",
    elephant : "éléphant",
    giraffe : "girafe",
    horse : "cheval",
    lion : "lion",
    monkey : "singe",
    pig : "cochon",
    rhinoceros : "rhinocéros",
    sealions : "otaries",
    tiger : "tigre",
    walrus : "morse",
    ambulance : "ambulance",
    busy_tone : "signal occupé",
    carhorn : "enceinte du véhicule",
    carhorn1 : "enceinte 1 du véhicule",
    doorbell : "sonnette de porte",
    engine : "moteur",
    laser : "laser",
    meebot : "meeBot",
    police_car_1 : "voiture de police 1",
    police_car_2 : "voiture de police 2",
    ringtones : "sonneries",
    robot : "robot",
    telephone_call : "appel téléphonique",
    touch_tone : "clavier",
    wave : "saluer",
    id_happy : "joie",
    id_jingya : "surprise",
    id_relei : "pleurs",
    id_leiguang : "larmes clignotantes",
    id_shangxin : "tristesse",
    id_yun : "étourdissement",
    id_cry : "pleurer",
    id_fadai : "stupéfaction",
    id_zhayan : "clin d'œil",
    id_haixiu : "timidité",
    id_shanshuo : "scintillement",
    id_huxi : "respiration",
    id_fengshan : "ventilateur",
    id_yugua : "essuie-glace",
    id_repet_error_hint : "Nom déjà enregistré.",
    id_deng : "arc-en-ciel",
    id_disco : "disco",
    id_caise : "superposition des couleurs",
    id_sanyuanse : "couleurs primaires",
    command : "commander",
    emotion : "émotion",
    cheer : "acclamation",
    transfiguration : "transformer",
    happy : "content",
    yawn : "bâillement",
    snoring : "ronflement",
    surprise : "surprise",
    actingcute : "mignonne",
    angry : "en colère",
    fail : "échec",
    lose : "perdu",
    received : "recevoir",
    complete : "achevée",
    cover : "bouclier",
    move : "bouge toi",
    doubt : "question",
    nonsense : "délirant",
    emotion_engine : "moteur",
    cheerful : "joyeux",
    support : "soutien",
    yes : "oui",
    come_and_play : "chanson 1",
    flexin : "chanson 2",
    london_bridge : "chanson 3",
    yankee_doodle : "chanson 4",
    variable_inputrule_msg : "Impossible de commencer par un chiffre. Les caractères spéciaux ne sont pas pris en charge. Un maximum de %1 caractères ou %2 caractères chinois peut être saisi.",
    recording_placeholder : "Nom d'enregistrement",
    sysVoiceName : "voix",
    sysActionName : "nouvelle action",
    posture_named_popup_placeholder : "action",
    recording_name_repea : "Désolé, le nom d'enregistrement que vous avez saisi est déjà utilisé",
    save_fail : "Échec de la sauvegarde de l'effet sonore",
    not_file : "Le fichier d'enregistrement n'existe pas",
    error_param : "Erreur de paramètre",
    sys_sound_name : "effets sonores du système",
    has_no_record_authority : "L'appareil actuel n'a pas accès aux enregistrements",
    porject_alert_content_02 : "Les opérations du service de base contiennent une erreur. Le message d'erreur",
    project_has_no_change : "Le programme en cours ne peut être modifié",
    newProjectName : "nouveau projet",
    add_project_pop_title : "nom du projet",
    add_project_placeholder : "nom du projet",
    porject_alert_content_01 : "Le nom de l'article existe déjà. Veuillez saisir un autre nom.",
    porject_alert_content_06 : "Projet enregistré",
    porject_alert_content_10 : "Veuillez faire glisser vers la gauche pour supprimer 1 action avant d'en ajouter une nouvelle.",
    porject_alert_content_11 : "Veuillez faire glisser vers la gauche pour supprimer 1 enregistrement avant d'en ajouter un nouveau.",
    porject_alert_content_04 : "Lecture du projet impossible",
    porject_alert_content_05 : "Désolé, le bloc du programme dans le fichier de lecture des éléments contient des erreurs !",
    close_blue : "La fonctionnalité Bluetooth est activée, le modèle se déconnecte-t-il ?",
    cancel_btn : "annuler",
    sure_btn : "OK",
    id_sensor_gyroscope : "gyroscope",
    x_axie : "angle de roulis",
    y_axie : "angle d'attaque",
    z_axie : "angle de cap",
    id_sensor : "capteur infrarouge",
    current_block_disabled : "Le bloc du programme actuel n'est pas disponible",
    id_copy_instruction : "copier la commande",
    id_copy_current : "copier actuel",
    id_copy_current_all : "actuel et inférieur",
    motion_placeholder : "mes actions",
    sys_motion_name : "actions système",
    motion_name_repea : "Désolé, le nom d'action actuel est déjà utilisé !",
    return : "Arrière",
    exit_popup_title : "conseils",
    exit_tips : "Le programme en cours ne peut être enregistré, souhaitez-vous néanmoins quitter ?",
    version_title : "Infos version Blockly",
    version_des : "Vous avez la dernière version de Blockly",
    version_btn : "Retourner à une version antérieure",
    blockly_guide1 : "Taper ici pour voir la rubrique Aide et les infos version de Blockly",
    blockly_guide2 : "Taper ici pour passer à une version antérieure de Blockly",
    guide_go : "sauter",
    version_msg : "Infos de mise à jour de version",
    update_record : "Historique de mise à jour",
    attention : "remarque",
    sure : "OK",
    record1 : "Optimisation de l'outil de programmation visuelle Blockly en améliorant l'expérience et la stabilité.",
    record2 : "Optimisation du popup pour les réglages de paramètres de commandes, avec des réglages de paramètres de commandes plus intuitifs.",
    record3 : "Optimisation des catégories de commandes, plusieurs commandes ajoutées, compréhension plus facile et intuitive.",
    record4 : "Le nouveau Blockly peut ne pas exécuter de précédents programmes ! Vous pouvez les exécuter avec une version antérieure.",
    no_circle_servo_info : "Aucun servo en mode Roue (rotation possible sur 360°). Voulez-vous en configurer un ?",
    no_common_servo_info : "Aucun servo en mode Angle (rotation possible selon la plage désignée). Voulez-vous en configurer un ?",
    no_circle_servo : "Le servo du modèle en cours n'est pas en mode rotation à 360° ",
    no_rotate_servo : "Le modèle en cours ne dispose d'aucun servo en mode angulaire",
    servo_changed_tips : "Le mode servo a été modifié. Veuillez redéfinir les paramètres.",
    edit_cancel : "annuler",
    edit_save : "enregistrer",
    edit_delete : "supprimer",
    id_math_remainder : "reste",
    id_math_round : "arrondir",
    id_math_ceil : "en haut",
    id_math_floor : "vers le bas",
    id_math_integer : "entier",
    id_math_odd : "nombre impair",
    id_math_even : "nombre pair",
    id_math_prime : "nombre premier",
    id_math_positive : "nombre positif",
    id_math_negative : "nombre négatif",
    release : "Relâcher",
    click : "appuyer",
    db_click : "appuyer deux fois",
    press_hold : "appuyer et maintenir",
    touch_sensor : "capteur tactile",
    status : "l'état est",
    id_sensor_set_gyroscope : "définir le gyroscope",
    id_sensor_angle_to_zero : "tous les angles à 0°",
    id_sensor_angle : "angle",
    gyroscope : "gyroscope",
    touch_tips : "Le modèle actuel n'est pas connecté à un capteur tactile.",
    gyroscope_tips : "Le modèle actuel n'est pas connecté à un capteur gyroscopique.",
    lights_tips : "Le modèle en cours n'est connecté à aucune lumière",
    disconnected : "Déconnecté",
    current_value : "valeur actuelle",
    recordTime_too_short : "le temps d'enregistrement est trop court",
    id_math_is : "est",
    project_unsaved : "Non enregistré",
    edit_edittemp : "modifier",
    name_empty : "le nom est requis",
    reminder_cannot_zero : "le diviseur ne peut pas être 0",
    infrared_tips : "Le modèle actuel n'est pas connecté à un capteur infrarouge.",
    project_not_saved : "ne pas enregistrer",
    var_name_repea : "Désolé, le nom de la variable actuelle a été utilisé!",
    nubmer_cannot_negative : "Excédent, dividende, diviseur ne peut pas être négatif",
    yu_cannot_zero : "Le reste ne peut pas être nul",
    id_motion_turn_stop : "S'arrêter",
    servo : "servo",
    electric_machinery : "moteur",
    electric_machinery_rotate : "pivoter",
    electric_machinery_rotate_speed : "vitesse",
    electric_machinery_rotate_speed_minns : "RPM",
    when_ultrasonic_sensor : "lorsque le capteur à ultrasons",
    ultrasonic_sensor : "capteur à ultrasons",
    ultrasonic_tips : "Le modèle actuel n'est pas connecté à un capteur à ultrasons",
    ultrasonic_lights : "voyant ultrason",
    infrared_ultrasonic_tips : "Le modèle actuel n'est connecté à aucun capteur infrarouge ni capteur à ultrasons",
    guide_step1 : "Dans l'onglet Programmation, vous pouvez consulter les programmes de robot",
    guide_step2 : "et programmer votre propre robot",
    guide_step3 : "Appliquez votre connaissance acquise grâce à la Base de formation afin de programmer votre robot Jimu !",
    current_has_disabled_block : "Certains blocs ne sont pas disponibles dans le programme actuel.",
    id_helloworld : "'Bonjour ! Je suis Jimu'",
};