var MSG = {
    id_events : "eventi",
    id_motion : "spostamenti",
    id_control : "controllo",
    id_acousto_optic : "visualizza",
    id_sensors : "sensori",
    id_math : "matematica",
    id_variable : "variabile",
    id_function : "funzioni",
    id_start : "avvia",
    id_when_start : "fai clic su \"Esegui\" per iniziare",
    id_go_to_start : "vai all'inizio",
    id_motion_speed : "velocità",
    id_motion_continued : "durata",
    id_motion_angle : "angolo",
    id_motion_distance : "riflettività",
    id_motion_second : "s",
    id_motion_degree : "grado",
    id_motion_step : "fasi",
    id_motion_execution : "esegui azione",
    id_motion_stop : "ferma azione",
    id_motion_myaction : "le mie azioni",
    id_motion_time : "durata",
    id_motion_millisecond : "ms",
    id_motion_go_forward : "avanti",
    id_motion_go_back : "indietro",
    id_motion_go_left : "gira a sx",
    id_motion_go_right : "gira a dx",
    id_motion_speed_normal : "intermedio",
    id_motion_speed_fast : "veloce",
    id_motion_speed_faster : "molto veloce",
    id_motion_speed_slow : "lento",
    id_motion_speed_slower : "molto lento",
    id_motion_steer_gear : "servomotore",
    id_motion_turn_angle : "ruota",
    id_motion_turn_rotation : "ruota",
    id_motion_turn_clockwise : "senso orario",
    id_motion_turn_unclockwise : "senso antiorario",
    id_while : "durante",
    id_repeat : "ripeti",
    id_control_wait : "attendi",
    id_control_repeat : "ripeti",
    id_control_wait_for : "attendi fino",
    id_control_repeat_times : "volte",
    id_until : "fino a",
    id_control_seconds : "ms",
    id_control_execution : "esegui",
    id_control_then : "quindi",
    id_control_infinite_loop : "ripeti esecuzione",
    id_acousto_play_tone : "riproduci melodia",
    id_acousto_beat : "tempo",
    id_acousto_play_sound : "riproduci effetto",
    id_acousto_mysound : "la mia voce",
    id_acousto_stop_play : "ferma riproduzione",
    id_acousto_lights_on : "accendi",
    id_acousto_color : "colore",
    id_acousto_continued : "durata",
    id_acousto_second : "s",
    id_acousto_left : "faro sx",
    id_acousto_right : "faro dx",
    id_acousto_eyes_lights : "faro occhi",
    id_acousto_brightness : "luminosità",
    id_acousto_bgMusic : "musica di sottofondo",
    id_acousto_bgLight : "luce di sottofondo",
    id_acousto_emotions : "espressione",
    id_acousto_scenelight : "luce display",
    id_acousto_custom : "luce personalizzata",
    id_acousto_r : "rosso",
    id_acousto_g : "verde",
    id_acousto_b : "blu",
    id_acousto_times : "volte",
    id_all_lightup : "tutto luminoso",
    id_self_defined : "personalizza",
    id_events_when : "quando",
    id_events_clicked : "viene toccato",
    id_events_when_device : "quando il cell/tablet",
    id_events_when_front_obstacle : "quando ci sono alcuni ostacoli davanti",
    id_events_when_obstacle : "quando il sensore RI",
    id_events_cm : "cm",
    event_click : "tocca",
    event_start : "avvia",
    id_events_move_right : "vai a dx",
    id_events_move_left : "vai a sx",
    id_events_move_up : "vai su",
    id_events_move_down : "vai giù",
    id_events_move_forward : "avanza",
    id_events_move_back : "vai indietro",
    ahead_obstacle : "ostacoli davanti",
    obstacle_distance : "distanza dall'ostacolo",
    phone_pad : "cell/tablet",
    tilt_right : "inclina a destra",
    tilt_left : "inclina a sinistra",
    tilt_up : "inclina verso l'alto",
    tilt_down : "inclina verso il basso",
    tilt_swing : "inclina per oscillare",
    id_sensor_IR_sensor : "sensore IR",
    id_sensor_reflectance_between_obstacle : "distanza dall'ostacolo",
    id_sensor_device : "cell/tablet",
    low_power : "basso consumo",
    create_variable : "nuova variabile",
    rename_variable : "rinomina variabile",
    variable1 : "variabile 1",
    variable_take : "imposta",
    variable_set_to : "come",
    variable_value : "il valore di",
    variable_placeholder : "Inserire nome variabile",
    increase : "aumenta",
    reduce : "diminuisci",
    id_math_and : "e",
    id_math_or : "o",
    id_math_not : "non",
    define_function : "definisci funzione",
    rename_function : "Rinomina funzione",
    beat_2 : "2",
    beat_1 : "1",
    beat_2_1 : "1/2",
    beat_4_1 : "1/4",
    beat_8_1 : "1/8",
    id_all : "tutto",
    animal : "animale",
    machine : "macchina",
    recording : "registrazione",
    bear : "orso",
    bird : "uccello",
    chicken : "gallina",
    cow : "mucca",
    dog : "cane",
    elephant : "elefante",
    giraffe : "giraffa",
    horse : "cavallo",
    lion : "leone",
    monkey : "scimmia",
    pig : "maiale",
    rhinoceros : "rinoceronte",
    sealions : "leoni marini",
    tiger : "tigre",
    walrus : "tricheco",
    ambulance : "ambulanza",
    busy_tone : "tono occupato",
    carhorn : "altoparlante veicolo",
    carhorn1 : "altoparlante veicolo 1",
    doorbell : "campanello",
    engine : "motore",
    laser : "laser",
    meebot : "meebot",
    police_car_1 : "auto della polizia 1",
    police_car_2 : "auto della polizia 2",
    ringtones : "suonerie",
    robot : "robot",
    telephone_call : "chiamata",
    touch_tone : "composizione a toni",
    wave : "saluta",
    id_happy : "felice",
    id_jingya : "sorpreso",
    id_relei : "lacrime",
    id_leiguang : "lacrime luminose",
    id_shangxin : "triste",
    id_yun : "frastornato",
    id_cry : "che piange",
    id_fadai : "sbalordito",
    id_zhayan : "occhiolino",
    id_haixiu : "timido",
    id_shanshuo : "scintilla",
    id_huxi : "respiro",
    id_fengshan : "ventilatore",
    id_yugua : "tergicristalli",
    id_repet_error_hint : "Nome già salvato.",
    id_deng : "7 indicatori colorati",
    id_disco : "disco",
    id_caise : "impilamento colori",
    id_sanyuanse : "colori primari",
    command : "comando",
    emotion : "emozione",
    cheer : "rallegrare",
    transfiguration : "trasformare",
    happy : "contento",
    yawn : "sbadiglio",
    snoring : "russare",
    surprise : "sorpresa",
    actingcute : "carina",
    angry : "arrabbiato",
    fail : "fallimento",
    lose : "perduto",
    received : "ricevere",
    complete : "completare",
    cover : "scudo",
    move : "mossa",
    doubt : "domanda",
    nonsense : "delirante",
    emotion_engine : "motore",
    cheerful : "gioioso",
    support : "supporto",
    yes : "sì",
    come_and_play : "brano 1",
    flexin : "brano 2",
    london_bridge : "brano 3",
    yankee_doodle : "brano 4",
    variable_inputrule_msg : "Non può iniziare con una cifra. Impossibile inserire caratteri speciali. È possibile inserire un massimo di %1 caratteri o %2 caratteri cinesi.",
    recording_placeholder : "Inserisci un nome di registrazione",
    sysVoiceName : "voce",
    sysActionName : "nuova azione",
    posture_named_popup_placeholder : "azione",
    recording_name_repea : "Spiacenti, il nome della registrazione inserito è già stato usato",
    save_fail : "Impossibile salvare effetto sonoro",
    not_file : "File registrazione inesistente",
    error_param : "Errore parametri",
    sys_sound_name : "effetti sonori del sistema",
    has_no_record_authority : "Il dispositivo corrente non ha accesso alle registrazioni",
    porject_alert_content_02 : "Errore nel funzionamento del servizio di base. Mess. errore",
    project_has_no_change : "Il programma corrente non ha subito modifiche",
    newProjectName : "nuovo progetto",
    add_project_pop_title : "nome progetto",
    add_project_placeholder : "nome progetto",
    porject_alert_content_01 : "Nome elemento già esistente. Inseriscilo di nuovo.",
    porject_alert_content_06 : "Progetto salvato",
    porject_alert_content_10 : "Scorrere a sx per eliminare 1 azione, quindi aggiungerne una nuova.",
    porject_alert_content_11 : "Scorrere a sx per eliminare 1 registrazione, quindi aggiungerne una nuova.",
    porject_alert_content_04 : "Impossibile leggere il progetto",
    porject_alert_content_05 : "Spiacenti, il blocco programma nel file degli elementi letti contiene errori.",
    close_blue : "Il Bluetooth è connesso. Si disconnette?",
    cancel_btn : "annulla",
    sure_btn : "OK",
    id_sensor_gyroscope : "giroscopio",
    x_axie : "angolo di rollio",
    y_axie : "angolo di inclinazione",
    z_axie : "angolo girodirezionale",
    id_sensor : "sensore IR",
    current_block_disabled : "Blocco programma corrente non disponibile",
    id_copy_instruction : "copia comando",
    id_copy_current : "copia corrente",
    id_copy_current_all : "corrente e in basso",
    motion_placeholder : "le mie azioni",
    sys_motion_name : "azioni sistema",
    motion_name_repea : "Spiacenti, il nome dell'azione corrente è già stato usato!",
    return : "Indietro",
    exit_popup_title : "suggerimenti",
    exit_tips : "Il programma corrente non è stato salvato. Uscire?",
    version_title : "Info versione Blockly",
    version_des : "Hai la versione di Blockly più recente",
    version_btn : "Ripristina versione precedente",
    blockly_guide1 : "Tocca qui per la guida e info sulla versione di Blockly",
    blockly_guide2 : "Tocca qui per passare a una versione precedente di Blockly",
    guide_go : "ignora",
    version_msg : "Info aggiornamento versione",
    update_record : "Cronologia aggiornamenti",
    attention : "nota",
    sure : "OK",
    record1 : "Strumento di programmazione visiva Blockly ottimizzato per una migliore esperienza e stabilità.",
    record2 : "Popup per impostazioni parametri di comando ottimizzato con impostazioni più intuitive.",
    record3 : "Categorie comandi ottimizzate, aggiunto diversi comandi, resi più intuitivi e di più semplice utilizzo.",
    record4 : "La nuova versione di Blockly potrebbe non eseguire i programmi precedenti! È possibile ripristinare una versione precedente per eseguirli.",
    no_circle_servo_info : "Nessuna modalità ruota del servomotore attualmente disponibile (è possibile effettuare una rotazione di 360°). Configurarne una?",
    no_common_servo_info : "Nessuna modalità di angolazione del servomotore attualmente disponibile (è possibile effettuare una rotazione entro un intervallo designato). Configurarne una?",
    no_circle_servo : "Servo del modello corrente privo di rotazione 360°",
    no_rotate_servo : "Modello corrente non dispone di servo con mod. angolare",
    servo_changed_tips : "Modalità servomotore cambiata. Reimpostare i parametri.",
    edit_cancel : "annulla",
    edit_save : "salva",
    edit_delete : "elimina",
    id_math_remainder : "resto",
    id_math_round : "arrotondamento",
    id_math_ceil : "su",
    id_math_floor : "giù",
    id_math_integer : "numero intero",
    id_math_odd : "numero dispari",
    id_math_even : "numero pari",
    id_math_prime : "numero primo",
    id_math_positive : "numero positivo",
    id_math_negative : "numero negativo",
    release : "Rilascia",
    click : "fai clic",
    db_click : "fai doppio clic",
    press_hold : "premi Sospendi",
    touch_sensor : "sensore a sfioramento",
    status : "lo stato è",
    id_sensor_set_gyroscope : "imposta giroscopio",
    id_sensor_angle_to_zero : "tutti gli angoli a 0°",
    id_sensor_angle : "angolo",
    gyroscope : "giroscopio",
    touch_tips : "Il modello corrente non è collegato a un sensore a sfioramento",
    gyroscope_tips : "Il modello corrente non è collegato a un sensore giroscopico",
    lights_tips : "Modello corrente non connesso ad alcun indicatore",
    disconnected : "Scollegato",
    current_value : "valore corrente",
    recordTime_too_short : "il tempo di registrazione è troppo breve",
    id_math_is : "è",
    project_unsaved : "Non salvato",
    edit_edittemp : "modifica",
    name_empty : "il nome è obbligatorio",
    reminder_cannot_zero : "il divisore non può essere 0",
    infrared_tips : "Il modello corrente non è collegato a un sensore a infrarossi",
    project_not_saved : "non salvare",
    var_name_repea : "Siamo spiacenti, il nome della variabile corrente è stato utilizzato!",
    nubmer_cannot_negative : "Surplus, dividendo, divisore non possono essere negativi",
    yu_cannot_zero : "Il resto non può essere zero",
    id_motion_turn_stop : "Arresta",
    servo : "servomotore",
    electric_machinery : "motore",
    electric_machinery_rotate : "ruota",
    electric_machinery_rotate_speed : "velocità",
    electric_machinery_rotate_speed_minns : "giri/min",
    when_ultrasonic_sensor : "quando il sensore a ultrasuoni",
    ultrasonic_sensor : "sensore a ultrasuoni",
    ultrasonic_tips : "Il modello corrente non è collegato a un sensore a ultrasuoni",
    ultrasonic_lights : "luce a ultrasuoni",
    infrared_ultrasonic_tips : "Il modello corrente non è collegato a un sensore a infrarossi o a ultrasuoni",
    guide_step1 : "Nel laboratorio di programmazione, puoi visualizzare i programmi del robot",
    guide_step2 : "e programma il tuo robot",
    guide_step3 : "Applica le tue conoscenze apprese nel centro di formazione per programmare il tuo robot Jimu",
    current_has_disabled_block : "Alcuni blocchi non sono disponibili nel programma corrente.",
    id_helloworld : "'Ciao a tutti! Io sono Jimu'",
};