var MSG = {
    id_events : "이벤트",
    id_motion : "이동",
    id_control : "제어",
    id_acousto_optic : "표시",
    id_sensors : "센서",
    id_math : "수학",
    id_variable : "변수",
    id_function : "함수",
    id_start : "시작",
    id_when_start : "‘실행’을 클릭하여 시작",
    id_go_to_start : "시작으로 이동",
    id_motion_speed : "속도",
    id_motion_continued : "시간",
    id_motion_angle : "각도",
    id_motion_distance : "반사율",
    id_motion_second : "s",
    id_motion_degree : "도",
    id_motion_step : "걸음",
    id_motion_execution : "작업 실행",
    id_motion_stop : "작업 정지",
    id_motion_myaction : "내 작업",
    id_motion_time : "시간",
    id_motion_millisecond : "ms",
    id_motion_go_forward : "앞으로",
    id_motion_go_back : "뒤로",
    id_motion_go_left : "좌회전",
    id_motion_go_right : "우회전",
    id_motion_speed_normal : "중간",
    id_motion_speed_fast : "빠름",
    id_motion_speed_faster : "매우 빠름",
    id_motion_speed_slow : "느림",
    id_motion_speed_slower : "매우 느림",
    id_motion_steer_gear : "서보",
    id_motion_turn_angle : "회전",
    id_motion_turn_rotation : "회전",
    id_motion_turn_clockwise : "시계 방향",
    id_motion_turn_unclockwise : "반시계 방향",
    id_while : "동안",
    id_repeat : "반복",
    id_control_wait : "대기",
    id_control_repeat : "반복",
    id_control_wait_for : "다음 때까지 대기",
    id_control_repeat_times : "회",
    id_until : "까지",
    id_control_seconds : "ms",
    id_control_execution : "실행",
    id_control_then : "다음",
    id_control_infinite_loop : "실행 반복",
    id_acousto_play_tone : "플레이 튠",
    id_acousto_beat : "템포",
    id_acousto_play_sound : "플레이 효과",
    id_acousto_mysound : "내 음성",
    id_acousto_stop_play : "재생 정지",
    id_acousto_lights_on : "조명 켜기",
    id_acousto_color : "색상",
    id_acousto_continued : "시간",
    id_acousto_second : "s",
    id_acousto_left : "왼쪽 램프",
    id_acousto_right : "오른쪽 램프",
    id_acousto_eyes_lights : "눈 램프",
    id_acousto_brightness : "밝기",
    id_acousto_bgMusic : "배경 음악",
    id_acousto_bgLight : "배경 조명",
    id_acousto_emotions : "감정",
    id_acousto_scenelight : "조명 디스플레이",
    id_acousto_custom : "사용자 지정 조명",
    id_acousto_r : "빨강",
    id_acousto_g : "초록",
    id_acousto_b : "파랑",
    id_acousto_times : "회",
    id_all_lightup : "모두 밝음",
    id_self_defined : "사용자 지정",
    id_events_when : "때",
    id_events_clicked : "탭되었을",
    id_events_when_device : "폰/태블릿이",
    id_events_when_front_obstacle : "전면에 장애물이 있을 때",
    id_events_when_obstacle : "IR 센서가",
    id_events_cm : "cm",
    event_click : "탭",
    event_start : "시작",
    id_events_move_right : "오른쪽 이동",
    id_events_move_left : "왼쪽 이동",
    id_events_move_up : "위로 이동",
    id_events_move_down : "아래로 이동",
    id_events_move_forward : "앞으로 이동",
    id_events_move_back : "뒤로 이동",
    ahead_obstacle : "전면 장애물",
    obstacle_distance : "장애물까지의 거리",
    phone_pad : "폰/태블릿",
    tilt_right : "오른쪽 기울이기",
    tilt_left : "왼쪽 기울이기",
    tilt_up : "위로 기울이기",
    tilt_down : "아래로 기울이기",
    tilt_swing : "기울여 돌리기",
    id_sensor_IR_sensor : "IR 센서",
    id_sensor_reflectance_between_obstacle : "장애물로부터의 거리",
    id_sensor_device : "폰/태블릿",
    low_power : "저전력",
    create_variable : "새 변수",
    rename_variable : "변수 이름 변경",
    variable1 : "변수 1",
    variable_take : "설정",
    variable_set_to : "로",
    variable_value : "의 값",
    variable_placeholder : "변수 이름을 입력하세요.",
    increase : "증가",
    reduce : "감소",
    id_math_and : "및",
    id_math_or : "또는",
    id_math_not : "not",
    define_function : "함수 정의",
    rename_function : "함수 이름 변경",
    beat_2 : "2",
    beat_1 : "1",
    beat_2_1 : "1/2",
    beat_4_1 : "1/4",
    beat_8_1 : "1/8",
    id_all : "전체",
    animal : "동물",
    machine : "기계",
    recording : "기록",
    bear : "곰",
    bird : "새",
    chicken : "닭",
    cow : "소",
    dog : "개",
    elephant : "코끼리",
    giraffe : "기린",
    horse : "말",
    lion : "사자",
    monkey : "원숭이",
    pig : "돼지",
    rhinoceros : "코뿔소",
    sealions : "바다사자",
    tiger : "호랑이",
    walrus : "바다코끼리",
    ambulance : "구급차",
    busy_tone : "통화 중 톤",
    carhorn : "차량 스피커",
    carhorn1 : "차량 스피커 1",
    doorbell : "초인종",
    engine : "엔진",
    laser : "레이저",
    meebot : "미봇",
    police_car_1 : "경찰차 1",
    police_car_2 : "경찰차 2",
    ringtones : "벨소리",
    robot : "로봇",
    telephone_call : "전화",
    touch_tone : "터치톤",
    wave : "웨이브",
    id_happy : "즐거움",
    id_jingya : "놀람",
    id_relei : "눈물",
    id_leiguang : "반짝이는 눈물",
    id_shangxin : "슬픔",
    id_yun : "어지러움",
    id_cry : "울음",
    id_fadai : "현혹",
    id_zhayan : "깜박임",
    id_haixiu : "수줍음",
    id_shanshuo : "반짝임",
    id_huxi : "입김",
    id_fengshan : "팬",
    id_yugua : "와이퍼",
    id_repet_error_hint : "이름이 이미 저장됨.",
    id_deng : "7색 조명",
    id_disco : "Disco",
    id_caise : "컬러 스태킹",
    id_sanyuanse : "기본 색상",
    command : "명령",
    emotion : "감정",
    cheer : "격려",
    transfiguration : "변환",
    happy : "행복",
    yawn : "하품 소리",
    snoring : "쿨쿨",
    surprise : "놀람",
    actingcute : "귀엽다",
    angry : "성난",
    fail : "실패",
    lose : "잃어버린",
    received : "받다",
    complete : "완전한",
    cover : "방패",
    move : "움직임",
    doubt : "문제",
    nonsense : "미쳐 날뛰는",
    emotion_engine : "엔진",
    cheerful : "즐거운",
    support : "지원하다",
    yes : "예",
    come_and_play : "노래 1",
    flexin : "노래 2",
    london_bridge : "노래 3",
    yankee_doodle : "노래 4",
    variable_inputrule_msg : "숫자로 시작할 수 없습니다. 특수 문자를 입력할 수 없습니다. 최대 %1 문자 또는 %2 중국어 문자를 입력할 수 있습니다.",
    recording_placeholder : "기록 이름을 입력하십시오",
    sysVoiceName : "음성",
    sysActionName : "새 작업",
    posture_named_popup_placeholder : "작동",
    recording_name_repea : "죄송합니다, 입력된 기록 이름이 사용되었습니다.",
    save_fail : "음향 효과 저장 실패",
    not_file : "기록 파일이 존재하지 않습니다.",
    error_param : "매개 변수 오류",
    sys_sound_name : "시스템 음향 효과",
    has_no_record_authority : "현 장치는 기록에 액세스할 수 없습니다.",
    porject_alert_content_02 : "베이스 서비스 작업 오류 오류 메시지",
    project_has_no_change : "현재 프로그램이 변경되지 않았습니다.",
    newProjectName : "새 프로젝트",
    add_project_pop_title : "프로젝트 이름",
    add_project_placeholder : "프로젝트 이름",
    porject_alert_content_01 : "아이템 이름이 이미 존재합니다. 다시 입력해주십시오.",
    porject_alert_content_06 : "프로젝트 저장됨",
    porject_alert_content_10 : "왼쪽으로 밀어 1개 작업을 삭제하고 새 작업을 추가하세요.",
    porject_alert_content_11 : "왼쪽으로 밀어 1개 기록을 삭제하고 새 작업을 추가하세요.",
    porject_alert_content_04 : "프로젝트 읽기 실패",
    porject_alert_content_05 : "죄송합니다, 읽기 항목 파일의 프로그램 블록에 오류가 있습니다.",
    close_blue : "Bluetooth가 연결되었습니까, 분리되었습니까?",
    cancel_btn : "취소",
    sure_btn : "확인",
    id_sensor_gyroscope : "자이로스코프",
    x_axie : "롤 각도",
    y_axie : "피치 각도",
    z_axie : "헤딩 각도",
    id_sensor : "IR 센서",
    current_block_disabled : "현 프로그램 블록을 사용할 수 없음",
    id_copy_instruction : "명령 복사",
    id_copy_current : "현재 복사",
    id_copy_current_all : "현재 및 아래",
    motion_placeholder : "내 작업",
    sys_motion_name : "시스템 작업",
    motion_name_repea : "죄송합니다, 현 작업 이름이 사용되었습니다!",
    return : "뒤로",
    exit_popup_title : "도움말",
    exit_tips : "현재 프로그램이 저장되지 않았습니다, 계속하시겠습니까, 종료하시겠습니까?",
    version_title : "Blockly 버전 정보",
    version_des : "Blockly 버전이 최신 버전입니다.",
    version_btn : "이전 버전으로 되돌리기",
    blockly_guide1 : "도움말 및 Blockly 버전 정보를 보려면 여기를 탭하세요.",
    blockly_guide2 : "이전 Blockly 버전으로 전환하려면 여기를 탭하세요.",
    guide_go : "건너뛰기",
    version_msg : "버전 업데이트 정보",
    update_record : "업데이트 내역",
    attention : "주",
    sure : "확인",
    record1 : "경험과 안정성을 개선함으로써 Blockly 비주얼 프로그래밍 도구 최적화.",
    record2 : "보다 직관적인 명령 매개 변수 설정으로 명령 매개 변수 설정을 위한 팝업 최적화.",
    record3 : "명령 카테고리 최적화, 명령 몇 가지 추가, 보다 직관적이고 이해하기 쉬운 명령.",
    record4 : "새 Blockly는 이전 프로그램을 실행하지 못할 수도 있습니다! 이전 버전으로 되돌리면 실행할 수 있습니다.",
    no_circle_servo_info : "현재 바퀴 모드 서보(360° 회전 가능)가 없습니다. 설정하시겠습니까?",
    no_common_servo_info : "현재 각도 모드 서보(지정된 범위로 회전 가능)가 없습니다. 설정하시겠습니까?",
    no_circle_servo : "현재 모델의 서보는 360도 회전 모드가 제공되지 않습니다.",
    no_rotate_servo : "현재 장치에 각도 모드 서보가 없습니다.",
    servo_changed_tips : "서보 모드가 변경되었습니다. 매개 변수를 다시 설정하세요.",
    edit_cancel : "취소",
    edit_save : "저장",
    edit_delete : "삭제",
    id_math_remainder : "나머지",
    id_math_round : "반올림",
    id_math_ceil : "쪽으로",
    id_math_floor : "하위",
    id_math_integer : "정수",
    id_math_odd : "홀수",
    id_math_even : "우수",
    id_math_prime : "소수",
    id_math_positive : "정수",
    id_math_negative : "음수",
    release : "해제",
    click : "클릭",
    db_click : "더블 클릭",
    press_hold : "홀드 누르기",
    touch_sensor : "터치 센서",
    status : "상태는",
    id_sensor_set_gyroscope : "자이로스코프 설정",
    id_sensor_angle_to_zero : "모든 각도를 0으로",
    id_sensor_angle : "각도",
    gyroscope : "자이로스코프",
    touch_tips : "현재 모델이 터치 센서에 연결되어 있지 않습니다.",
    gyroscope_tips : "현재 모델이 자이로스코프 센서에 연결되어 있지 않습니다.",
    lights_tips : "현재 모델이 어떤 라이트하고도 연결되어 있지 않습니다.",
    disconnected : "연결 해제됨",
    current_value : "현재 값",
    recordTime_too_short : "녹음 시간이 너무 짧다.",
    id_math_is : "~이다.",
    project_unsaved : "저장되지 않았습니다.",
    edit_edittemp : "수정",
    name_empty : "이름은 비워 둘 수 없습니다.",
    reminder_cannot_zero : "제수는 0이 될 수 없다.",
    infrared_tips : "현재 모델이 적외선 센서에 연결되어 있지 않습니다.",
    project_not_saved : "저장하지 마십시오.",
    var_name_repea : "죄송합니다. 현재 변수 이름이 사용되었습니다!",
    nubmer_cannot_negative : "잉여, 배당, 제수는 음수 일 수 없다.",
    yu_cannot_zero : "나머지는 0이 될 수 없습니다.",
    id_motion_turn_stop : "정지",
    servo : "서보",
    electric_machinery : "모터",
    electric_machinery_rotate : "회전",
    electric_machinery_rotate_speed : "속도",
    electric_machinery_rotate_speed_minns : "rpm",
    when_ultrasonic_sensor : "초음파 센서가",
    ultrasonic_sensor : "초음파 센서",
    ultrasonic_tips : "현재 모델이 초음파 센서에 연결되어 있지 않습니다.",
    ultrasonic_lights : "초음파 조명",
    infrared_ultrasonic_tips : "현재 모델이 IR 센서 및 초음파 센서에 연결되어 있지 않습니다.",
    guide_step1 : "Programming Lab에서는 로봇 프로그램을 볼 수 있습니다.",
    guide_step2 : "그리고 직접 로봇을 프로그래밍해볼 수 있습니다.",
    guide_step3 : "Training Base에서 배운 지식을 적용하여 Jimu 로봇을 프로그래밍해보세요!",
    current_has_disabled_block : "현재 프로그램에서 일부 블록을 사용할 수 없습니다.",
    id_helloworld : "'안녕하세요, 여러분, 저는 Jimu예요.'",
};