var MSG = {
    id_events : "wydarzenia",
    id_motion : "ruchy",
    id_control : "sterowanie",
    id_acousto_optic : "pokaż",
    id_sensors : "czujniki",
    id_math : "obliczenia",
    id_variable : "zmienna",
    id_function : "funkcje",
    id_start : "start",
    id_when_start : "kliknij „Uruchom”, aby rozpocząć",
    id_go_to_start : "wróć",
    id_motion_speed : "prędk.",
    id_motion_continued : "czas trwania",
    id_motion_angle : "kąt",
    id_motion_distance : "współczynnik odbicia",
    id_motion_second : "s",
    id_motion_degree : "stopnie",
    id_motion_step : "kroki",
    id_motion_execution : "wykonaj działanie",
    id_motion_stop : "zatrzymaj działanie",
    id_motion_myaction : "moje działania",
    id_motion_time : "czas trwania",
    id_motion_millisecond : "ms",
    id_motion_go_forward : "do przodu",
    id_motion_go_back : "do tyłu",
    id_motion_go_left : "skręć w lewo",
    id_motion_go_right : "skręć w prawo",
    id_motion_speed_normal : "średnio",
    id_motion_speed_fast : "szybko",
    id_motion_speed_faster : "b. szybko",
    id_motion_speed_slow : "wolno",
    id_motion_speed_slower : "bardzo wolno",
    id_motion_steer_gear : "siłownik",
    id_motion_turn_angle : "obrót",
    id_motion_turn_rotation : "obrót",
    id_motion_turn_clockwise : "prawoskr.",
    id_motion_turn_unclockwise : "lewoskrętny",
    id_while : "chwila",
    id_repeat : "powtórz",
    id_control_wait : "zaczekaj",
    id_control_repeat : "powtórz",
    id_control_wait_for : "poczekaj, aż",
    id_control_repeat_times : "razy",
    id_until : "do",
    id_control_seconds : "ms",
    id_control_execution : "wykonaj",
    id_control_then : "następnie",
    id_control_infinite_loop : "powtórz wykonanie",
    id_acousto_play_tone : "odtwórz utwór",
    id_acousto_beat : "tempo",
    id_acousto_play_sound : "odtwórz efekt",
    id_acousto_mysound : "mój głos",
    id_acousto_stop_play : "zatrzymaj odtwarzanie",
    id_acousto_lights_on : "oświetl",
    id_acousto_color : "kolor",
    id_acousto_continued : "czas trwania",
    id_acousto_second : "s",
    id_acousto_left : "lewa lampa",
    id_acousto_right : "prawa lampa",
    id_acousto_eyes_lights : "oświetlenie oczu",
    id_acousto_brightness : "jasność",
    id_acousto_bgMusic : "muzyka w tle",
    id_acousto_bgLight : "oświetlenie tła",
    id_acousto_emotions : "wyraz twarzy",
    id_acousto_scenelight : "oświetlenie",
    id_acousto_custom : "niestandardowe światło",
    id_acousto_r : "czerwony",
    id_acousto_g : "zielony",
    id_acousto_b : "niebieski",
    id_acousto_times : "razy",
    id_all_lightup : "wszystko jasne",
    id_self_defined : "niestandardowy",
    id_events_when : "kiedy",
    id_events_clicked : "zostanie dotknięty",
    id_events_when_device : "gdy telefon/tablet",
    id_events_when_front_obstacle : "gdy z przodu znajdują się przeszkody",
    id_events_when_obstacle : "gdy czujnik podczerwieni",
    id_events_cm : "cm",
    event_click : "dotknij",
    event_start : "start",
    id_events_move_right : "przesuń w prawo",
    id_events_move_left : "przesuń w lewo",
    id_events_move_up : "przesuń w górę",
    id_events_move_down : "przesuń w dół",
    id_events_move_forward : "przesuń do przodu",
    id_events_move_back : "przesuń do tyłu",
    ahead_obstacle : "przeszkody z przodu",
    obstacle_distance : "odległość do przeszkody",
    phone_pad : "telefon/tablet",
    tilt_right : "pochyl w prawo",
    tilt_left : "poch. w lew",
    tilt_up : "pochyl w górę",
    tilt_down : "pochyl w dół",
    tilt_swing : "przechylenia obrotowe",
    id_sensor_IR_sensor : "czujnik podczerwieni",
    id_sensor_reflectance_between_obstacle : "odległość od przeszkody",
    id_sensor_device : "telefon/tablet",
    low_power : "niski poziom zasilania",
    create_variable : "nowa zmienna",
    rename_variable : "zmień nazwę zmiennej",
    variable1 : "zmienna 1",
    variable_take : "ustaw",
    variable_set_to : "jako",
    variable_value : "wartość",
    variable_placeholder : "Wprowadź nazwę zmiennej",
    increase : "zwiększ",
    reduce : "zmniejsz",
    id_math_and : "i",
    id_math_or : "lub",
    id_math_not : "nie",
    define_function : "zdefiniuj funkcję",
    rename_function : "zmień nazwę funkcji",
    beat_2 : "2",
    beat_1 : "1",
    beat_2_1 : "1/2",
    beat_4_1 : "1/4",
    beat_8_1 : "1/8",
    id_all : "wsz.",
    animal : "zwierzę",
    machine : "urządzenie",
    recording : "nagrywanie",
    bear : "niedźwiedź",
    bird : "ptak",
    chicken : "kurczak",
    cow : "krowa",
    dog : "pies",
    elephant : "słoń",
    giraffe : "żyrafa",
    horse : "koń",
    lion : "lew",
    monkey : "małpa",
    pig : "świnia",
    rhinoceros : "nosorożec",
    sealions : "uchatka",
    tiger : "tygrys",
    walrus : "mors",
    ambulance : "ambulans",
    busy_tone : "sygnał dźwiękowy zajętości",
    carhorn : "głośnik pojazdu",
    carhorn1 : "głośnik pojazdu 1",
    doorbell : "dzwonek u drzwi",
    engine : "silnik",
    laser : "laser",
    meebot : "meebot",
    police_car_1 : "samochód policyjny 1",
    police_car_2 : "samochód policyjny 2",
    ringtones : "dzwonki",
    robot : "robot",
    telephone_call : "rozmowa telefoniczna",
    touch_tone : "telefon z klawiaturą",
    wave : "fala",
    id_happy : "zadowolony",
    id_jingya : "zaskoczony",
    id_relei : "łzy",
    id_leiguang : "błyszczące łzy",
    id_shangxin : "smutny",
    id_yun : "oszołomiony",
    id_cry : "płakać",
    id_fadai : "zszokowany",
    id_zhayan : "mruga",
    id_haixiu : "nieśmiały",
    id_shanshuo : "błysk",
    id_huxi : "oddech",
    id_fengshan : "wentylator",
    id_yugua : "wycieraczki",
    id_repet_error_hint : "Nazwa już zapisana.",
    id_deng : "7 kolorowych diod",
    id_disco : "disco",
    id_caise : "nakładanie kolorów",
    id_sanyuanse : "kolory podstawowe",
    command : "rozkaz",
    emotion : "dopingować",
    cheer : "dopingować",
    transfiguration : "przekształcać",
    happy : "szczęśliwy",
    yawn : "ziewać",
    snoring : "chrapanie",
    surprise : "niespodzianka",
    actingcute : "uroczy",
    angry : "zły",
    fail : "niepowodzenie",
    lose : "stracony",
    received : "otrzymać",
    complete : "kompletny",
    cover : "tarcza",
    move : "ruszaj się",
    doubt : "pytanie",
    nonsense : "bredzenie",
    emotion_engine : "silnik",
    cheerful : "radosny",
    support : "wsparcie",
    yes : "tak",
    come_and_play : "utwór 1",
    flexin : "utwór 2",
    london_bridge : "utwór 3",
    yankee_doodle : "utwór 4",
    variable_inputrule_msg : "Nie może zaczynać się od cyfry. Nie można wprowadzić specjalnych znaków. Maksymalna dozwolona liczba znaków: %1 (zwykłe) lub %2 (chińskie).",
    recording_placeholder : "Wprowadź nazwę nagrania",
    sysVoiceName : "głos",
    sysActionName : "nowe działanie",
    posture_named_popup_placeholder : "akcja",
    recording_name_repea : "Niestety wprowadzona nazwa nagrania została wykorzystana",
    save_fail : "Nie udało się zapisać efektu dźwiękowego",
    not_file : "Plik nagrania nie istnieje",
    error_param : "Błąd parametru",
    sys_sound_name : "efekty dźwiękowe systemu",
    has_no_record_authority : "Bieżące urządzenie nie ma dostępu do nagrań",
    porject_alert_content_02 : "Błąd operacji usługi podstawowej. Komunikat o błędzie",
    project_has_no_change : "Bieżący program nie uległ zmianie",
    newProjectName : "nowy projekt",
    add_project_pop_title : "nazwa projektu",
    add_project_placeholder : "nazwa projektu",
    porject_alert_content_01 : "Nazwa elementu już istnieje. Wprowadź ponownie.",
    porject_alert_content_06 : "Projekt zapisany",
    porject_alert_content_10 : "Przesuń w lewo, aby usunąć 1 działanie, a następnie dodaj nowe.",
    porject_alert_content_11 : "Przesuń w lewo, aby usunąć 1 nagranie, a następnie dodaj nowe.",
    porject_alert_content_04 : "Nie udało się odczytać projektu",
    porject_alert_content_05 : "Niestety blok programowy w pliku pozycji odczytu zawiera błędy.",
    close_blue : "Bluetooth jest podłączony, czy na pewno odłączyć?",
    cancel_btn : "anuluj",
    sure_btn : "OK",
    id_sensor_gyroscope : "żyroskop",
    x_axie : "kąt wznosz.",
    y_axie : "kąt pochylenia",
    z_axie : "kąt kursu",
    id_sensor : "czuj podcz.",
    current_block_disabled : "Bieżący blok programowy nie jest dostępny",
    id_copy_instruction : "polecenie kopiowania",
    id_copy_current : "kopiuj bieżący",
    id_copy_current_all : "bieżący i niższe",
    motion_placeholder : "moje działania",
    sys_motion_name : "działania systemu",
    motion_name_repea : "Niestety bieżąca nazwa działania została wykorzystana!",
    return : "Powr.",
    exit_popup_title : "porady",
    exit_tips : "Bieżący program nie zostanie zapisany, czy na pewno zakończyć?",
    version_title : "Informacje o wersji programu Blockly",
    version_des : "Masz najnowszą wersję programu Blockly",
    version_btn : "Przywróć wcześniejszą wersję",
    blockly_guide1 : "Dotknij tutaj, aby wyświetlić Pomoc i informacje o wersji programu Blockly",
    blockly_guide2 : "Dotknij tutaj, aby przełączyć do wcześniejszej wersji programu Blockly",
    guide_go : "pomiń",
    version_msg : "Informacje o aktualizacji wersji",
    update_record : "Historia aktualizacji",
    attention : "uwaga",
    sure : "OK",
    record1 : "Zoptymalizowano narzędzie do programowania wizualnego Blockly, poprawiając wygodę użytkowania i stabilność.",
    record2 : "Zoptymalizowano okienko ustawień parametrów poleceń, dodając więcej intuicyjnych ustawień parametrów poleceń.",
    record3 : "Zoptymalizowano kategorie poleceń, dodano kilka poleceń oraz zwiększono ich intuicyjność i zrozumiałość.",
    record4 : "Nowy program Blockly może nie być w stanie uruchomić poprzednich programów! Można przywrócić wcześniejszą wersję do uruchomienia.",
    no_circle_servo_info : "Obecnie brak siłownika w trybie kołowym (może się obracać o 360°). Czy chcesz taki skonfigurować?",
    no_common_servo_info : "Obecnie brak siłownika w trybie kątowym (może się obracać w wyznaczonym zakresie). Czy chcesz taki skonfigurować?",
    no_circle_servo : "Siłownik bieżącego modelu nie jest wyposażony w tryb obrotu o 360 stopni.",
    no_rotate_servo : "Bieżący sprzęt nie ma siłownika trybu kątowego",
    servo_changed_tips : "Tryb siłownika został zmieniony. Ponownie ustaw parametry.",
    edit_cancel : "anuluj",
    edit_save : "zapisz",
    edit_delete : "usuń",
    id_math_remainder : "reszta",
    id_math_round : "zaokrąglanie",
    id_math_ceil : "w górę",
    id_math_floor : "na dół",
    id_math_integer : "liczba całkowita",
    id_math_odd : "liczba nieparzysta",
    id_math_even : "liczba parzysta",
    id_math_prime : "liczba pierwsza",
    id_math_positive : "Liczba dodatnia",
    id_math_negative : "liczba ujemna",
    release : "Uwolnij",
    click : "kliknij",
    db_click : "podwójne kliknięcie",
    press_hold : "wciśnij „Zawieś”",
    touch_sensor : "czujnik dotykowy",
    status : "status to",
    id_sensor_set_gyroscope : "ustaw żyroskop",
    id_sensor_angle_to_zero : "wszystkie kąty na zero stopni",
    id_sensor_angle : "kąt",
    gyroscope : "żyroskop",
    touch_tips : "Bieżący model nie jest podłączony do czujnika dotykowego.",
    gyroscope_tips : "Bieżący model nie jest podłączony do czujnika żyroskopowego.",
    lights_tips : "Bieżący model nie jest podłączony do żadnego oświetlenia",
    disconnected : "Niepodłączone",
    current_value : "wartość bieżąca",
    recordTime_too_short : "czas nagrywania jest za krótki",
    id_math_is : "jest",
    project_unsaved : "Nie zapisane",
    edit_edittemp : "edytuj",
    name_empty : "imie jest wymagane",
    reminder_cannot_zero : "dzielnik nie może być równy 0",
    infrared_tips : "Bieżący model nie jest podłączony do czujnika podczerwieni.",
    project_not_saved : "nie oszczędzaj",
    var_name_repea : "Niestety, użyto bieżącej nazwy zmiennej!",
    nubmer_cannot_negative : "Nadwyżka, dywidenda, dzielnik nie mogą być ujemne",
    yu_cannot_zero : "Reszta nie może wynosić zero",
    id_motion_turn_stop : "Zatrzymaj",
    servo : "serwomechanizm",
    electric_machinery : "silnik",
    electric_machinery_rotate : "obrót",
    electric_machinery_rotate_speed : "prędkość",
    electric_machinery_rotate_speed_minns : "obr./min",
    when_ultrasonic_sensor : "gdy czujnik ultradźwiękowy",
    ultrasonic_sensor : "czujnik ultradźwiękowy",
    ultrasonic_tips : "Bieżący model nie jest podłączony do czujnika ultradźwiękowego.",
    ultrasonic_lights : "światło ultradźwiękowe",
    infrared_ultrasonic_tips : "Bieżący robot nie jest podłączony do czujnika podczerwieni i czujnika ultradźwiękowego.",
    guide_step1 : "W Laboratorium programowania możesz wyświetlić programy dla robotów",
    guide_step2 : "i zaprogramować własnego.",
    guide_step3 : "Wykorzystaj w praktyce wiedzę zdobytą w Bazie szkoleniowej i zaprogramuj robota Jimu!",
    current_has_disabled_block : "Niektóre klocki są niedostępne w bieżącym programie.",
    id_helloworld : "'Witaj świecie! Jestem Jimu'",
};