var MSG = {
    id_events : "eventos",
    id_motion : "movimentações",
    id_control : "controlo",
    id_acousto_optic : "espetáculo",
    id_sensors : "sensores",
    id_math : "matemática",
    id_variable : "variável",
    id_function : "funções",
    id_start : "iniciar",
    id_when_start : "toque em \"Executar\" para iniciar",
    id_go_to_start : "ir p/ início",
    id_motion_speed : "velocidade",
    id_motion_continued : "duração",
    id_motion_angle : "ângulo",
    id_motion_distance : "refletância",
    id_motion_second : "s",
    id_motion_degree : "grau",
    id_motion_step : "passos",
    id_motion_execution : "executar ação",
    id_motion_stop : "parar ação",
    id_motion_myaction : "minhas ações",
    id_motion_time : "duração",
    id_motion_millisecond : "ms",
    id_motion_go_forward : "avançar",
    id_motion_go_back : "recuar",
    id_motion_go_left : "virar à esquerda",
    id_motion_go_right : "virar à direita",
    id_motion_speed_normal : "média",
    id_motion_speed_fast : "rápida",
    id_motion_speed_faster : "muito rápida",
    id_motion_speed_slow : "lenta",
    id_motion_speed_slower : "muito lenta",
    id_motion_steer_gear : "servomotor",
    id_motion_turn_angle : "rodar",
    id_motion_turn_rotation : "rodar",
    id_motion_turn_clockwise : "para a direita",
    id_motion_turn_unclockwise : "para a esquerda",
    id_while : "enquanto",
    id_repeat : "repetir",
    id_control_wait : "aguardar",
    id_control_repeat : "repetir",
    id_control_wait_for : "aguardar até",
    id_control_repeat_times : "vezes",
    id_until : "até",
    id_control_seconds : "ms",
    id_control_execution : "executar",
    id_control_then : "então",
    id_control_infinite_loop : "repetir execução",
    id_acousto_play_tone : "reproduzir melodia",
    id_acousto_beat : "ritmo",
    id_acousto_play_sound : "reproduzir efeito",
    id_acousto_mysound : "minha voz",
    id_acousto_stop_play : "para reprodução",
    id_acousto_lights_on : "iluminar",
    id_acousto_color : "cor",
    id_acousto_continued : "duração",
    id_acousto_second : "s",
    id_acousto_left : "lâmpada esquerda",
    id_acousto_right : "lâmpada direita",
    id_acousto_eyes_lights : "lâmpada dos olhos",
    id_acousto_brightness : "brilho",
    id_acousto_bgMusic : "música ambiente",
    id_acousto_bgLight : "iluminação ambiente",
    id_acousto_emotions : "expressão",
    id_acousto_scenelight : "apresentação de luzes",
    id_acousto_custom : "personalizar luz",
    id_acousto_r : "vermelho",
    id_acousto_g : "verde",
    id_acousto_b : "azul",
    id_acousto_times : "vezes",
    id_all_lightup : "radiante",
    id_self_defined : "personalizado",
    id_events_when : "quando",
    id_events_clicked : "é tocado",
    id_events_when_device : "quando o telefone/tablet",
    id_events_when_front_obstacle : "quando existem obstáculos em frente",
    id_events_when_obstacle : "quando o sensor de IV",
    id_events_cm : "cm",
    event_click : "tocar",
    event_start : "iniciar",
    id_events_move_right : "mover p/ dir.",
    id_events_move_left : "mover p/ esq.",
    id_events_move_up : "mover p/ cima",
    id_events_move_down : "mover p/ baixo",
    id_events_move_forward : "avançar",
    id_events_move_back : "retroceder",
    ahead_obstacle : "obstáculos em frente",
    obstacle_distance : "distância até ao obstáculo",
    phone_pad : "telefone/tablet",
    tilt_right : "inclinar para a direita",
    tilt_left : "inclinar para a esquerda",
    tilt_up : "inclinar para cima",
    tilt_down : "inclinar para baixo",
    tilt_swing : "inclinar oscilação",
    id_sensor_IR_sensor : "sensor de IV",
    id_sensor_reflectance_between_obstacle : "distância do obstáculo",
    id_sensor_device : "telefone/tablet",
    low_power : "baixa potência",
    create_variable : "nova variável",
    rename_variable : "renomear variável",
    variable1 : "variável 1",
    variable_take : "definir",
    variable_set_to : "como",
    variable_value : "o valor de",
    variable_placeholder : "Introduza o nome da variável",
    increase : "aumentar",
    reduce : "diminuir",
    id_math_and : "e",
    id_math_or : "ou",
    id_math_not : "não",
    define_function : "definir função",
    rename_function : "Renomear função",
    beat_2 : "2",
    beat_1 : "1",
    beat_2_1 : "1/2",
    beat_4_1 : "1/4",
    beat_8_1 : "1/8",
    id_all : "tudo",
    animal : "animal",
    machine : "máquina",
    recording : "gravação",
    bear : "urso",
    bird : "pássaro",
    chicken : "galinha",
    cow : "vaca",
    dog : "cão",
    elephant : "elefante",
    giraffe : "girafa",
    horse : "cavalo",
    lion : "leão",
    monkey : "macaco",
    pig : "porco",
    rhinoceros : "rinoceronte",
    sealions : "leões marinhos",
    tiger : "tigre",
    walrus : "morsa",
    ambulance : "ambulância",
    busy_tone : "tom de ocupado",
    carhorn : "altifalante do veículo",
    carhorn1 : "altifalante do veículo 1",
    doorbell : "campainha",
    engine : "motor",
    laser : "laser",
    meebot : "meebot",
    police_car_1 : "carro da polícia 1",
    police_car_2 : "carro da polícia 2",
    ringtones : "toques",
    robot : "robot",
    telephone_call : "chamada telefónica",
    touch_tone : "tom de toque",
    wave : "acenar",
    id_happy : "feliz",
    id_jingya : "surpreso",
    id_relei : "lágrimas",
    id_leiguang : "lágrimas intermitentes",
    id_shangxin : "triste",
    id_yun : "confuso",
    id_cry : "choroso",
    id_fadai : "surpreendido",
    id_zhayan : "piscar",
    id_haixiu : "tímido",
    id_shanshuo : "cintilar",
    id_huxi : "respirar",
    id_fengshan : "ventoinha",
    id_yugua : "limpadores",
    id_repet_error_hint : "Nome já guardado.",
    id_deng : "7 luzes coloridas",
    id_disco : "disco",
    id_caise : "empilhamento de cores",
    id_sanyuanse : "cores primárias",
    command : "comando",
    emotion : "emoção",
    cheer : "torcer",
    transfiguration : "transformar",
    happy : "feliz",
    yawn : "bocejar",
    snoring : "ronco",
    surprise : "surpresa",
    actingcute : "fofa",
    angry : "bravo",
    fail : "falha",
    lose : "perdido",
    received : "receber",
    complete : "completo",
    cover : "escudo",
    move : "mover",
    doubt : "questão",
    nonsense : "delirante",
    emotion_engine : "motor",
    cheerful : "alegre",
    support : "suporte",
    yes : "sim",
    come_and_play : "canção 1",
    flexin : "canção 2",
    london_bridge : "canção 3",
    yankee_doodle : "canção 4",
    variable_inputrule_msg : "Não pode começar com um dígito. Impossível introduzir caracteres especiais. Pode ser introduzido um máximo de %1 caracteres ou %2 caracteres chineses.",
    recording_placeholder : "Introduza um nome de gravação",
    sysVoiceName : "voz",
    sysActionName : "nova ação",
    posture_named_popup_placeholder : "ação",
    recording_name_repea : "Perdão, o nome da gravação que introduziu já existe",
    save_fail : "Falha ao guardar o efeito sonoro",
    not_file : "O ficheiro de gravação não existe",
    error_param : "Erro de parâmetro",
    sys_sound_name : "efeitos sonoros do sistema",
    has_no_record_authority : "O dispositivo atual não tem acesso às gravações",
    porject_alert_content_02 : "Erro na operação do serviço base. Mensagem de erro",
    project_has_no_change : "O programa atual não foi alterado",
    newProjectName : "novoProjeto",
    add_project_pop_title : "nome do projeto",
    add_project_placeholder : "nome do projeto",
    porject_alert_content_01 : "O nome do item já existe. Introduza-o novamente.",
    porject_alert_content_06 : "Projeto guardado",
    porject_alert_content_10 : "Deslize para a esquerda para eliminar 1 ação e adicionar uma nova.",
    porject_alert_content_11 : "Deslize para a esquerda para eliminar 1 gravação e adicionar uma nova.",
    porject_alert_content_04 : "Falha ao ler o projeto",
    porject_alert_content_05 : "Perdão, o bloco de programação no ficheiro de leitura do item contém erros.",
    close_blue : "O Bluetooth está ligado. Pretende desligá-lo?",
    cancel_btn : "cancelar",
    sure_btn : "OK",
    id_sensor_gyroscope : "giroscópio",
    x_axie : "ângulo de rotação",
    y_axie : "ângulo de inclinação longitudinal",
    z_axie : "ângulo de direção",
    id_sensor : "sensor de IV",
    current_block_disabled : "Bloco de programação atual não disponível",
    id_copy_instruction : "copiar comando",
    id_copy_current : "copiar atual",
    id_copy_current_all : "atual e mais baixo",
    motion_placeholder : "minhas ações",
    sys_motion_name : "ações do sistema",
    motion_name_repea : "Perdão, o nome da ação atual já foi utilizado!",
    return : "Retroceder",
    exit_popup_title : "sugestões",
    exit_tips : "O programa atual não foi guardado. Pretende sair?",
    version_title : "Informação da versão Blockly",
    version_des : "Esta é a versão mais recente do Blockly",
    version_btn : "Reverter para uma versão anterior",
    blockly_guide1 : "Tocar aqui para ver a ajuda e a informação da versão Blockly",
    blockly_guide2 : "Tocar aqui para trocar para uma versão mais antiga do Blockly",
    guide_go : "ignorar",
    version_msg : "Informação de atualização da versão",
    update_record : "Histórico de atualizações",
    attention : "nota",
    sure : "OK",
    record1 : "Ferramenta de programação visual Blockly otimizada com o melhoramento da experiência e da estabilidade.",
    record2 : "Caixa de diálogo para as definições de parâmetros do comando otimizada, com mais definições de parâmetros de comando intuitivas.",
    record3 : "Categorias de comando otimizadas, vários comandos adicionados e tornando-os mais intuitivos e de fácil compreensão.",
    record4 : "O novo Blockly poderá não conseguir executar programas anteriores! Pode reverter para uma versão anterior para os executar.",
    no_circle_servo_info : "Atualmente não existe um servo do modo de roda (pode rodar 360°). Precisa de configurar um agora?",
    no_common_servo_info : "Atualmente não existe um servo do modo de ângulo (pode dentro de um intervalo designado). Precisa de configurar um agora?",
    no_circle_servo : "O servo do modelo atual não contém um modo de rotação de 360 graus.",
    no_rotate_servo : "O equip. atual não contém servo de modo angular",
    servo_changed_tips : "O modo do servo foi alterado. Defina os parâmetros novamente.",
    edit_cancel : "cancelar",
    edit_save : "guardar",
    edit_delete : "eliminar",
    id_math_remainder : "restante",
    id_math_round : "arredondamento",
    id_math_ceil : "acima",
    id_math_floor : "baixa",
    id_math_integer : "inteiro",
    id_math_odd : "número ímpar",
    id_math_even : "numero par",
    id_math_prime : "número primo",
    id_math_positive : "número positivo",
    id_math_negative : "número negativo",
    release : "Soltar",
    click : "clicar",
    db_click : "clicar duas vezes",
    press_hold : "premir continuamente",
    touch_sensor : "sensor de toque",
    status : "o estado é",
    id_sensor_set_gyroscope : "definir giroscópio",
    id_sensor_angle_to_zero : "todos os ângulos p/ zero graus",
    id_sensor_angle : "ângulo",
    gyroscope : "giroscópio",
    touch_tips : "O modelo atual não se encontra ligado a um sensor tátil",
    gyroscope_tips : "O modelo atual não se encontra ligado a um sensor giroscópio",
    lights_tips : "O modelo atual não se encontra ligado a uma luz",
    disconnected : "Desligado",
    current_value : "valor atual",
    recordTime_too_short : "o tempo de gravação é muito curto",
    id_math_is : "é",
    project_unsaved : "Não salvo",
    edit_edittemp : "editar",
    name_empty : "o nome é obrigatório",
    reminder_cannot_zero : "o divisor não pode ser 0",
    infrared_tips : "O modelo atual não se encontra ligado a um sensor de infravermelhos",
    project_not_saved : "não salve",
    var_name_repea : "Desculpe, o nome da variável atual foi usado!",
    nubmer_cannot_negative : "Excedente, dividendo, divisor não pode ser negativo",
    yu_cannot_zero : "O restante não pode ser zero",
    id_motion_turn_stop : "Parar",
    servo : "servomotor",
    electric_machinery : "motor",
    electric_machinery_rotate : "rodar",
    electric_machinery_rotate_speed : "velocidade",
    electric_machinery_rotate_speed_minns : "rpm",
    when_ultrasonic_sensor : "quando o sensor ultra-sónico",
    ultrasonic_sensor : "sensor ultra-sónico",
    ultrasonic_tips : "O modelo atual não se encontra ligado a um sensor ultra-sónico",
    ultrasonic_lights : "luz ultra-sónica",
    infrared_ultrasonic_tips : "O modelo atual não se encontra ligado a um sensor de infravermelhos e sensor ultra-sónico",
    guide_step1 : "No Laboratório de programação, podes ver programações de robôs",
    guide_step2 : "e programar o teu próprio robô",
    guide_step3 : "Aplica os conhecimentos que adquiriste na Base de treino para programar o teu robô Jimu!",
    current_has_disabled_block : "Alguns blocos não estão disponíveis no programa atual.",
    id_helloworld : "'Olá, mundo! E sou o Jimu'",
};