var MSG = {
    id_events : "события",
    id_motion : "движения",
    id_control : "управление",
    id_acousto_optic : "показать",
    id_sensors : "датчики",
    id_math : "математика",
    id_variable : "переменная",
    id_function : "функции",
    id_start : "начать",
    id_when_start : "щелкните «запуск» для запуска",
    id_go_to_start : "перейти в начало",
    id_motion_speed : "скорость",
    id_motion_continued : "продолжительность",
    id_motion_angle : "угол",
    id_motion_distance : "коэффициент отражения",
    id_motion_second : "с",
    id_motion_degree : "угол",
    id_motion_step : "шагов",
    id_motion_execution : "выполнить действие",
    id_motion_stop : "остановить действие",
    id_motion_myaction : "мои действия",
    id_motion_time : "продолжительность",
    id_motion_millisecond : "мс",
    id_motion_go_forward : "вперед",
    id_motion_go_back : "назад",
    id_motion_go_left : "поворот влево",
    id_motion_go_right : "поворот вправо",
    id_motion_speed_normal : "средне",
    id_motion_speed_fast : "быстро",
    id_motion_speed_faster : "очень быстро",
    id_motion_speed_slow : "медленно",
    id_motion_speed_slower : "очень медленно",
    id_motion_steer_gear : "сервопривод",
    id_motion_turn_angle : "вращать",
    id_motion_turn_rotation : "вращать",
    id_motion_turn_clockwise : "по часовой стрелке",
    id_motion_turn_unclockwise : "против часовой стрелки",
    id_while : "по мере того, как",
    id_repeat : "повторить",
    id_control_wait : "ожидание",
    id_control_repeat : "повторить",
    id_control_wait_for : "ждать, пока",
    id_control_repeat_times : "раз",
    id_until : "до тех пор, пока",
    id_control_seconds : "мс",
    id_control_execution : "выполнять до",
    id_control_then : "затем",
    id_control_infinite_loop : "повторить выполнение",
    id_acousto_play_tone : "воспроизвести мелодию",
    id_acousto_beat : "темп",
    id_acousto_play_sound : "воспроизвести эффект",
    id_acousto_mysound : "мой голос",
    id_acousto_stop_play : "остановить воспроизведение",
    id_acousto_lights_on : "включить свет",
    id_acousto_color : "цвет",
    id_acousto_continued : "продолжительность",
    id_acousto_second : "с",
    id_acousto_left : "левая лампа",
    id_acousto_right : "правая лампа",
    id_acousto_eyes_lights : "лампа глаза",
    id_acousto_brightness : "яркость",
    id_acousto_bgMusic : "фоновая музыка",
    id_acousto_bgLight : "фоновый свет",
    id_acousto_emotions : "выражение",
    id_acousto_scenelight : "отображение света",
    id_acousto_custom : "пользовательский свет",
    id_acousto_r : "красный",
    id_acousto_g : "Зеленый",
    id_acousto_b : "синий",
    id_acousto_times : "раз",
    id_all_lightup : "все ярко",
    id_self_defined : "пользовательская",
    id_events_when : "когда",
    id_events_clicked : "нажато",
    id_events_when_device : "когда телефон/планшет",
    id_events_when_front_obstacle : "когда впереди имеются препятствия",
    id_events_when_obstacle : "когда ИК-датчик",
    id_events_cm : "см",
    event_click : "коснуться",
    event_start : "начать",
    id_events_move_right : "двигаться вправо",
    id_events_move_left : "двигаться влево",
    id_events_move_up : "двигаться вверх",
    id_events_move_down : "двигаться вниз",
    id_events_move_forward : "двигаться вперед",
    id_events_move_back : "двигаться назад",
    ahead_obstacle : "препятствия спереди",
    obstacle_distance : "расстояние до препятствия",
    phone_pad : "телефон/планшет",
    tilt_right : "наклон вправо",
    tilt_left : "наклон влево",
    tilt_up : "наклон вверх",
    tilt_down : "наклон вниз",
    tilt_swing : "наклон качения",
    id_sensor_IR_sensor : "ИК-датчик",
    id_sensor_reflectance_between_obstacle : "расстояние от препятствия",
    id_sensor_device : "телефон/планшет",
    low_power : "низкий уровень заряда",
    create_variable : "новая переменная",
    rename_variable : "переименовать переменную",
    variable1 : "переменная 1",
    variable_take : "задать",
    variable_set_to : "как",
    variable_value : "значение",
    variable_placeholder : "Введите имя переменной",
    increase : "увеличить",
    reduce : "уменьшить",
    id_math_and : "и",
    id_math_or : "или",
    id_math_not : "не",
    define_function : "определить функцию",
    rename_function : "переименовать функцию",
    beat_2 : "2",
    beat_1 : "1",
    beat_2_1 : "1/2",
    beat_4_1 : "1/4",
    beat_8_1 : "1/8",
    id_all : "все",
    animal : "животное",
    machine : "машина",
    recording : "запись",
    bear : "медведь",
    bird : "птица",
    chicken : "курица",
    cow : "корова",
    dog : "собака",
    elephant : "слон",
    giraffe : "жираф",
    horse : "лошадь",
    lion : "лев",
    monkey : "обезьяна",
    pig : "свинья",
    rhinoceros : "носорог",
    sealions : "морские львы",
    tiger : "тигр",
    walrus : "морж",
    ambulance : "скорая помощь",
    busy_tone : "сигнал «занято»",
    carhorn : "динамик транспортного средства",
    carhorn1 : "динамик транспортного средства 1",
    doorbell : "дверной звонок",
    engine : "двигатель",
    laser : "лазер",
    meebot : "мибот",
    police_car_1 : "полицейский автомобиль 1",
    police_car_2 : "полицейский автомобиль 2",
    ringtones : "мелодии звонка",
    robot : "робот",
    telephone_call : "телефонный звонок",
    touch_tone : "звук касания",
    wave : "волна",
    id_happy : "счастливый",
    id_jingya : "удивленный",
    id_relei : "слезы",
    id_leiguang : "кратковременные слезы",
    id_shangxin : "грустный",
    id_yun : "головокружение",
    id_cry : "плачь",
    id_fadai : "изумление",
    id_zhayan : "мигание",
    id_haixiu : "робкий",
    id_shanshuo : "вспышка",
    id_huxi : "дыхание",
    id_fengshan : "веер",
    id_yugua : "салфетки",
    id_repet_error_hint : "Название уже сохранено.",
    id_deng : "7 цветных огней",
    id_disco : "disco",
    id_caise : "многоярусная компоновка цветов",
    id_sanyuanse : "основные цвета",
    command : "команда",
    emotion : "эмоция",
    cheer : "ура",
    transfiguration : "преобразование",
    happy : "счастливый",
    yawn : "зевать",
    snoring : "храп",
    surprise : "сюрприз",
    actingcute : "милый",
    angry : "сердитый",
    fail : "недостаточность",
    lose : "потерял",
    received : "получать",
    complete : "полный",
    cover : "щит",
    move : "переехать",
    doubt : "вопрос",
    nonsense : "raving",
    emotion_engine : "двигатель",
    cheerful : "радостный",
    support : "поддержка",
    yes : "да",
    come_and_play : "песня 1",
    flexin : "песня 2",
    london_bridge : "песня 3",
    yankee_doodle : "песня 4",
    variable_inputrule_msg : "Не может начинаться с цифры. Нельзя вводить специальные символы. Можно ввести максимум %1 символов или %2 китайских иероглифов.",
    recording_placeholder : "Введите название записи",
    sysVoiceName : "голос",
    sysActionName : "новое действие",
    posture_named_popup_placeholder : "действие",
    recording_name_repea : "Извините, введенное название записи уже используется",
    save_fail : "Не удалось сохранить звуковой эффект",
    not_file : "Файл записи не существует",
    error_param : "Ошибка параметра",
    sys_sound_name : "звуковые эффекты системы",
    has_no_record_authority : "У текущего устройства нет доступа к записям",
    porject_alert_content_02 : "Ошибка в базовой операции обслуживания. Сообщение ошибки",
    project_has_no_change : "Текущая программа не изменена",
    newProjectName : "newProject",
    add_project_pop_title : "имя проекта",
    add_project_placeholder : "имя проекта",
    porject_alert_content_01 : "Название элемента уже существует. Повторите ввод.",
    porject_alert_content_06 : "Проект сохранен",
    porject_alert_content_10 : "Проведите влево, чтобы удалить 1 действие и затем добавьте новое.",
    porject_alert_content_11 : "Проведите влево, чтобы удалить 1 запись и затем добавьте новую.",
    porject_alert_content_04 : "Не удалось прочитать проект",
    porject_alert_content_05 : "Извините, блок программы в элементе считывания содержит ошибки!",
    close_blue : "Bluetooth подключен, отключить?",
    cancel_btn : "отмена",
    sure_btn : "ок",
    id_sensor_gyroscope : "гироскоп",
    x_axie : "угол вращения",
    y_axie : "угол наклона",
    z_axie : "угол курса",
    id_sensor : "ИК-датчик",
    current_block_disabled : "Текущий блок программы недоступен",
    id_copy_instruction : "скопировать команду",
    id_copy_current : "скопировать текущий",
    id_copy_current_all : "текущий и нижний",
    motion_placeholder : "мои действия",
    sys_motion_name : "системные действия",
    motion_name_repea : "Извините, текущее название действия уже используется!",
    return : "Назад",
    exit_popup_title : "советы",
    exit_tips : "Текущая программа не сохранена, продолжить выход？",
    version_title : "Информация о версии Blockly",
    version_des : "установлена последняя версия Blockly",
    version_btn : "Вернуться на раннюю версию",
    blockly_guide1 : "Коснитесь здесь для просмотра справки и информации о версии Blockly",
    blockly_guide2 : "Коснитесь здесь для возврата на раннюю версию Blockly",
    guide_go : "пропустить",
    version_msg : "Информация об обновлении версии",
    update_record : "История обновлений",
    attention : "примечание",
    sure : "ОК",
    record1 : "Визуальный инструмент программирования Blockly оптимизирован, путем улучшения стабильности и пользовательского опыта.",
    record2 : "Оптимизировано всплывающее окно настроек параметра команды, теперь предоставляющее более интуитивные настройки параметра команды.",
    record3 : "Оптимизированы категории команд, добавлены несколько команд, и они сделаны более интуитивными и простыми для понимания.",
    record4 : "Новый Blockly возможно не сможет запускать предыдущие программы! Для их запуска можно вернуться на более раннюю версию.",
    no_circle_servo_info : "В настоящий момент нет сервоприводов в режиме колеса (возможность вращения на 360°). Создать?",
    no_common_servo_info : "В настоящий момент нет сервоприводов в режиме угла (возможность поворота на заданный угол). Создать?",
    no_circle_servo : "Сервопривод текущей модели не оснащен режимом вращения на 360 градусов",
    no_rotate_servo : "Текущее оборудование не имеет сервоприводов в режиме угла",
    servo_changed_tips : "Режим сервопривода был изменен. Задайте параметры снова.",
    edit_cancel : "отмена",
    edit_save : "сохранить",
    edit_delete : "удалить",
    id_math_remainder : "остаток",
    id_math_round : "округление",
    id_math_ceil : "вверх",
    id_math_floor : "aşağı",
    id_math_integer : "целое",
    id_math_odd : "нечетное число",
    id_math_even : "четное число",
    id_math_prime : "простое число",
    id_math_positive : "положительное число",
    id_math_negative : "отрицательное число",
    release : "Выпустить",
    click : "щелчок",
    db_click : "двойной щелчок",
    press_hold : "нажмите Hold",
    touch_sensor : "датчик касания",
    status : "состояние",
    id_sensor_set_gyroscope : "установить гироскоп",
    id_sensor_angle_to_zero : "все углы на ноль градусов",
    id_sensor_angle : "угол",
    gyroscope : "гироскоп",
    touch_tips : "Текущая модель не подключена к датчику касания",
    gyroscope_tips : "Текущая модель не подключена к датчику гироскопа",
    lights_tips : "Текущая модель не подключена к свету",
    disconnected : "Отключено",
    current_value : "текущее значение",
    recordTime_too_short : "время записи слишком короткое",
    id_math_is : "является",
    project_unsaved : "Не сохранено",
    edit_edittemp : "редактировать",
    name_empty : "требуется имя",
    reminder_cannot_zero : "делитель не может быть 0",
    infrared_tips : "Текущая модель не подключена к инфракрасному датчику",
    project_not_saved : "не сохранять",
    var_name_repea : "Извините, имя текущей переменной было использовано!",
    nubmer_cannot_negative : "Избыток, дивиденд, делитель не может быть отрицательным",
    yu_cannot_zero : "Остальная часть не может быть равна нулю",
    id_motion_turn_stop : "Остановка",
    servo : "сервопривод",
    electric_machinery : "двигатель",
    electric_machinery_rotate : "повернуть",
    electric_machinery_rotate_speed : "скорость",
    electric_machinery_rotate_speed_minns : "об/мин",
    when_ultrasonic_sensor : "когда ультразвуковой датчик",
    ultrasonic_sensor : "ультразвуковой датчик",
    ultrasonic_tips : "Текущая модель не подключена к ультразвуковому датчику",
    ultrasonic_lights : "ультразвуковой фонарь",
    infrared_ultrasonic_tips : "Текущая модель не подключена к ИК-датчику и ультразвуковому датчику",
    guide_step1 : "В Лаборатории программирования можно просматривать программы роботов",
    guide_step2 : "и программировать собственного робота",
    guide_step3 : "Примените свои знания, полученные на Учебной базе, для программирования собственного робота Jimu!",
    current_has_disabled_block : "Некоторые блоки в настоящей программе недоступны.",
    id_helloworld : "'Привет, мир! Я – Jimu'",
};