var MSG = {
    id_events : "olaylar",
    id_motion : "hamle.",
    id_control : "kontrol",
    id_acousto_optic : "göst.",
    id_sensors : "sensörler",
    id_math : "mat.",
    id_variable : "değişken",
    id_function : "işlevler",
    id_start : "başlat",
    id_when_start : "başlmk için 'Git'e tıkla",
    id_go_to_start : "başlata gidin",
    id_motion_speed : "hız",
    id_motion_continued : "süre",
    id_motion_angle : "açı",
    id_motion_distance : "yansıtıcılık",
    id_motion_second : "s",
    id_motion_degree : "derece",
    id_motion_step : "adım",
    id_motion_execution : "eylemi gerçekleştir",
    id_motion_stop : "eylemi durdur",
    id_motion_myaction : "eylemlerim",
    id_motion_time : "süre",
    id_motion_millisecond : "ms",
    id_motion_go_forward : "ileri",
    id_motion_go_back : "geri",
    id_motion_go_left : "sola dön",
    id_motion_go_right : "sağa dön",
    id_motion_speed_normal : "orta",
    id_motion_speed_fast : "hızlı",
    id_motion_speed_faster : "çok hızlı",
    id_motion_speed_slow : "yavaş",
    id_motion_speed_slower : "çok yavaş",
    id_motion_steer_gear : "servo",
    id_motion_turn_angle : "döndür",
    id_motion_turn_rotation : "döndür",
    id_motion_turn_clockwise : "saat yönüne",
    id_motion_turn_unclockwise : "saat yönü tersine",
    id_while : "sırada",
    id_repeat : "tekrarla",
    id_control_wait : "bekle",
    id_control_repeat : "tekrarla",
    id_control_wait_for : "kadar bekle",
    id_control_repeat_times : "kez",
    id_until : "kadar",
    id_control_seconds : "ms",
    id_control_execution : "yürüt",
    id_control_then : "sonra",
    id_control_infinite_loop : "uygulamayı tekrarla",
    id_acousto_play_tone : "ses oynat",
    id_acousto_beat : "tempo",
    id_acousto_play_sound : "efekt oynat",
    id_acousto_mysound : "sesim",
    id_acousto_stop_play : "yeniden oynatmayı durdur",
    id_acousto_lights_on : "işıklandır",
    id_acousto_color : "renk",
    id_acousto_continued : "süre",
    id_acousto_second : "s",
    id_acousto_left : "sol lamba",
    id_acousto_right : "sağ lamba",
    id_acousto_eyes_lights : "masa lambası",
    id_acousto_brightness : "parlaklık",
    id_acousto_bgMusic : "fon müziği",
    id_acousto_bgLight : "fon lambası",
    id_acousto_emotions : "ifade",
    id_acousto_scenelight : "işık ekranı",
    id_acousto_custom : "özel ışık",
    id_acousto_r : "kırmızı",
    id_acousto_g : "yeşil",
    id_acousto_b : "mavi",
    id_acousto_times : "kez",
    id_all_lightup : "tümü aydınlk",
    id_self_defined : "özel",
    id_events_when : "üzerine",
    id_events_clicked : "basıldığında",
    id_events_when_device : "telefon/tabletin üzerine basıldığında",
    id_events_when_front_obstacle : "önde engel varken basıldığında",
    id_events_when_obstacle : "IR sensöre basıldığında",
    id_events_cm : "cm",
    event_click : "dokun",
    event_start : "başlat",
    id_events_move_right : "sağa taşı",
    id_events_move_left : "sola taşı",
    id_events_move_up : "yukarı taşı",
    id_events_move_down : "aşağı taşı",
    id_events_move_forward : "ileri taşı",
    id_events_move_back : "geri taşı",
    ahead_obstacle : "öndeki engeller",
    obstacle_distance : "engele olan mesafe",
    phone_pad : "telefon/tablet",
    tilt_right : "sağa eğ",
    tilt_left : "sola eğ",
    tilt_up : "yukarı eğ",
    tilt_down : "aşağı eğ",
    tilt_swing : "sallayark eğ",
    id_sensor_IR_sensor : "KÖ sensör",
    id_sensor_reflectance_between_obstacle : "engelden itibaren mesafe",
    id_sensor_device : "telefon/tablet",
    low_power : "düşük güç",
    create_variable : "yeni değişken",
    rename_variable : "değişkeni yeniden adlandır",
    variable1 : "değişken 1",
    variable_take : "değer",
    variable_set_to : "olarak",
    variable_value : "ayarla",
    variable_placeholder : "Değişkenin adını girin",
    increase : "artır",
    reduce : "azalt",
    id_math_and : "ve",
    id_math_or : "veya",
    id_math_not : "yok",
    define_function : "fonksiyonu tanımla",
    rename_function : "fonksiyonu yeniden adlandır",
    beat_2 : "2",
    beat_1 : "1",
    beat_2_1 : "1/2",
    beat_4_1 : "1/4",
    beat_8_1 : "1/8",
    id_all : "tümü",
    animal : "hayvan",
    machine : "makine",
    recording : "kaydedliyor",
    bear : "ayı",
    bird : "kuş",
    chicken : "tavuk",
    cow : "inek",
    dog : "köpk",
    elephant : "fil",
    giraffe : "zürafa",
    horse : "at",
    lion : "aslan",
    monkey : "maymun",
    pig : "domz",
    rhinoceros : "gergedan",
    sealions : "dnz aslan.",
    tiger : "kaplan",
    walrus : "mors",
    ambulance : "ambulans",
    busy_tone : "meşgul tonu",
    carhorn : "araç hoparlörü",
    carhorn1 : "araç hoparlörü 1",
    doorbell : "kapı zili",
    engine : "motor",
    laser : "lazer",
    meebot : "meebot",
    police_car_1 : "polis arabası 1",
    police_car_2 : "polis arabası 2",
    ringtones : "zil sesleri",
    robot : "robot",
    telephone_call : "telefon araması",
    touch_tone : "dokunma tonu",
    wave : "dalga",
    id_happy : "mutlu",
    id_jingya : "şaşırmış",
    id_relei : "gözyaşları",
    id_leiguang : "yanıp sönen gözyaşları",
    id_shangxin : "üzgün",
    id_yun : "sersemlemiş",
    id_cry : "ağla",
    id_fadai : "büyülenmiş",
    id_zhayan : "göz Kırp",
    id_haixiu : "utangaç",
    id_shanshuo : "flaş",
    id_huxi : "nefes Al",
    id_fengshan : "fan",
    id_yugua : "silecekler",
    id_repet_error_hint : "Ad zaten kayıtlı.",
    id_deng : "7 renkli ışıklar",
    id_disco : "disco",
    id_caise : "renk Yığınlama",
    id_sanyuanse : "ana Renkler",
    command : "emir",
    emotion : "duygu",
    cheer : "tezahürat",
    transfiguration : "dönüşme",
    happy : "mutlu",
    yawn : "esneme",
    snoring : "horlama",
    surprise : "sürpriz",
    actingcute : "sevimli",
    angry : "kızgın",
    fail : "başarısızlık",
    lose : "kayıp",
    received : "alma",
    complete : "tam",
    cover : "kalkan",
    move : "hareket Etmek",
    doubt : "soru",
    nonsense : "çılgın",
    emotion_engine : "motor",
    cheerful : "neşeli",
    support : "destek",
    yes : "evet",
    come_and_play : "şarkı 1",
    flexin : "şarkı 2",
    london_bridge : "şarkı 3",
    yankee_doodle : "şarkı 4",
    variable_inputrule_msg : "Bir rakam ile başlayamaz. Özel karakterler girilemez. Maksimum %1 veya %2 Çince karakter girilebilir.",
    recording_placeholder : "Lütfen bir kayıt adı girin",
    sysVoiceName : "ses",
    sysActionName : "yeni eylem",
    posture_named_popup_placeholder : "eylem",
    recording_name_repea : "Üzgünüz, girdiğiniz kayıt adı kullanılmış",
    save_fail : "Ses efekti kaydedilemedi",
    not_file : "Kayıt dosyası yok",
    error_param : "Parametre sorunu",
    sys_sound_name : "sistem ses efektleri",
    has_no_record_authority : "Geçerli cihazın kayıtlara erişimi yok",
    porject_alert_content_02 : "Taban hizmetlerinin çalıştırılmasında hata. Hata mesajı",
    project_has_no_change : "Mevcut program değiştirilmemiş",
    newProjectName : "yeniProje",
    add_project_pop_title : "proje adı",
    add_project_placeholder : "proje adı",
    porject_alert_content_01 : "Öge adı zaten mevcut. Lütfen tekrar girin.",
    porject_alert_content_06 : "Proje kaydedildi",
    porject_alert_content_10 : "1 eylemi silmek için sola kayın ve yeni bir tane ekleyin.",
    porject_alert_content_11 : "1 kaydı silmek için sola kayın ve yeni bir tane ekleyin.",
    porject_alert_content_04 : "Proje okunamadı",
    porject_alert_content_05 : "Üzgünüz, okuma öğesi dosyasındaki program bloğu hata içeriyor.",
    close_blue : "Bluetooth bağlı, kesilsin mi?",
    cancel_btn : "iptal et",
    sure_btn : "tmm",
    id_sensor_gyroscope : "cayroskop",
    x_axie : "yuvar. açısı",
    y_axie : "adım açısı",
    z_axie : "gittiği açı",
    id_sensor : "KÖ sensör",
    current_block_disabled : "Geçerli program bloğu kullanılamıyor",
    id_copy_instruction : "komutu kopyalayın",
    id_copy_current : "geçerli olanı kopyalayın",
    id_copy_current_all : "geçerli ve daha düşük",
    motion_placeholder : "eylemlerim",
    sys_motion_name : "sistem işlemleri",
    motion_name_repea : "Üzgünüz, geçerli işlem adı kullanılmış!",
    return : "Geri",
    exit_popup_title : "ipucu",
    exit_tips : "Mevcut program kaydedilmemiş, çıkmaya devam edilsin mi ?",
    version_title : "Blockly sürüm bilgisi",
    version_des : "En son Blockly sürümüne sahipsiniz",
    version_btn : "Bir önceki sürüme çevirin",
    blockly_guide1 : "Yardım ve Blockly sürüm bilgisini görmek için buraya dokunun",
    blockly_guide2 : "Bir önceki Blockly sürümüne geçmek için buraya dokunun",
    guide_go : "geç",
    version_msg : "Sürün güncelleme bilgisi",
    update_record : "Güncelleme geçmişi",
    attention : "not",
    sure : "tmm",
    record1 : "Tecrübe ve istikrar artırılarak Blockly görsel programlama aracı optimize edildi.",
    record2 : "Komut parametre ayarına ait açılır pencere daha fazla sezgisel komut parametre ayarıyla optimize edildi.",
    record3 : "Komut kategorileri optimize edildi, birkaç komut eklendi ve daha sezgisel ve kolay anlaşılır kılındı.",
    record4 : "Yeni Blockly önceki programlarda çalışmayabilir! Çalışması için bir önceki sürüme çevirebilirsiniz",
    no_circle_servo_info : "Şu anda servo tekerlek modu yok (360 ° döndürebiliyorsunuz). Bir tane ayarlamanız gerekiyor mu?",
    no_common_servo_info : "Halen açılı mod servo yok (belirlenmiş bir aralıkta dönüş yapabiliyor). Bir tane ayarlamanız gerekiyor mu?",
    no_circle_servo : "Mevcut modelin servosu 360° dönme modunu kapsamıyor",
    no_rotate_servo : "Mevcut ekipmanda açı modu servosu yok",
    servo_changed_tips : "Servo modu değiştirildi. Parametreleri tekrar ayarlayın.",
    edit_cancel : "iptal et",
    edit_save : "kaydet",
    edit_delete : "sil",
    id_math_remainder : "kalan",
    id_math_round : "yuvarlatma",
    id_math_ceil : "yukarı",
    id_math_floor : "aşağı",
    id_math_integer : "tamsayı",
    id_math_odd : "garip numara",
    id_math_even : "çift sayı",
    id_math_prime : "asal sayı",
    id_math_positive : "pozitif sayı",
    id_math_negative : "negatif sayı",
    release : "Bırak",
    click : "tıkla",
    db_click : "çift Tıkla",
    press_hold : "basılı Tut",
    touch_sensor : "doknmtk. sensör",
    status : "durum",
    id_sensor_set_gyroscope : "cayroskop ayarla",
    id_sensor_angle_to_zero : "tüm açılar sıfır dereceye",
    id_sensor_angle : "açı",
    gyroscope : "cayroskop",
    touch_tips : "Mevcut model dokunmatik sensöre bağlı değil",
    gyroscope_tips : "Mevcut model bir jiroskop sensörüne bağlı değil",
    lights_tips : "Mevcut model hiçbir ışığa bağlı değil",
    disconnected : "Bağlantı koptu",
    current_value : "mevcut değer",
    recordTime_too_short : "kayıt süresi çok kısa",
    id_math_is : "olduğu",
    project_unsaved : "kaydedilmedi",
    edit_edittemp : "düzenle",
    name_empty : "ad boş olamaz",
    reminder_cannot_zero : "bölen 0 olamaz",
    infrared_tips : "Mevcut model bir kızıl ötesi algılayıcıya bağlı değil",
    project_not_saved : "Kaydetme",
    var_name_repea : "Üzgünüz, geçerli değişken adı kullanıldı!",
    nubmer_cannot_negative : "Fazla, temettü, bölen negatif olamaz",
    yu_cannot_zero : "Kalan sıfır olamaz",
    id_motion_turn_stop : "Dur",
    servo : "servo",
    electric_machinery : "motor",
    electric_machinery_rotate : "döndür",
    electric_machinery_rotate_speed : "hız",
    electric_machinery_rotate_speed_minns : "rpm",
    when_ultrasonic_sensor : "ultrasonik sensöre basıldığında",
    ultrasonic_sensor : "ultrasonik sensör",
    ultrasonic_tips : "Mevcut model, ultrasonik sensöre bağlı değil",
    ultrasonic_lights : "ultrasonik ışık",
    infrared_ultrasonic_tips : "Geçerli model bir IR sensörüne ve ultrasonik sensöre bağlı değil",
    guide_step1 : "Programlama Laboratuvarında robot programlarını görüntüleyebilir",
    guide_step2 : "ve kendi robotunuzu programlayabilirsiniz",
    guide_step3 : "Jimu robotunuzu programlamak için Eğitim Üssünden edindiğiniz bilgileri uygulayın!",
    current_has_disabled_block : "Mevcut programda bazı bloklar kullanılamaz.",
    id_helloworld : "'Merhaba，dünya！ Ben Jimu'",
};