var courseData = {
    level: 1,
    stage: 1,
    knowledgePoint: 1,
    mission: 8,
    taskTitle: MSG['l1_s1_m8_' + window.moveType + '_title'] || MSG['l1_s1_m8_commonType_title'],
    helpList: {
        'commonType': [
            {
                'text': 'l1_help_004',
            },
            {
                'text': 'l1_help_003',
            }
        ],
    },    
    program: {
        'commonType': {// 普通类别
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="62" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_continued_second" id="ohEasCS1hai=o@!tYL13"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="HthezOgEnVroQAVmt1BC"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="28-N2*HahfOv2/uQZBGL"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="2xQ,PiDRO;I[6~eX70TM"><field name="TIME">1</field></shadow></value></block></next></block></next></block><block type="motion_speed_continued_second" id="!;$r}TZD?08^5iGYR|`d" x="262" y="307"><field name="directionType">TurnRight</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="0J3HI%qrGjTB8oM2VA@m"><field name="TIME">1</field></shadow></value></block><block type="motion_speed_continued_second" id=")lYGlL@9!!Dll#$IdcF-" x="89" y="421"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="UUp@B^xLYg!DoH3iYMkP"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="U)%s-Zq:_$TVMQG)ttvr"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="]Ra][}tzz5~{1]Bn2v~1"><field name="TIME">1</field></shadow></value></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="62" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_continued_second" id="ohEasCS1hai=o@!tYL13"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="HthezOgEnVroQAVmt1BC"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="!;$r}TZD?08^5iGYR|`d"><field name="directionType">TurnRight</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="0J3HI%qrGjTB8oM2VA@m"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id=")lYGlL@9!!Dll#$IdcF-"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="UUp@B^xLYg!DoH3iYMkP"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="U)%s-Zq:_$TVMQG)ttvr"><field name="directionType">TurnLeft</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="]Ra][}tzz5~{1]Bn2v~1"><field name="TIME">1</field></shadow></value></block></next></block></next></block></next></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_continued_second', name: ['speedType', 'MOTION_SPEED_CONTINUED_SECOND'] }
            ]
        },
        'doubleFeet': {// 双足
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_distance" id="wM^D9e?KxRA]I5|7+W{|"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="FB9[f)`]{j1[[QfG5b_Z"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="}DbxZI6rH/ArtD#IuNe4"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="2spCoAr=TDcC62T.MSPj"><field name="NUM">1</field></shadow></value></block></next></block></next></block><block type="motion_speed_distance" id="y7PxBIKHrV1+HWE_p+;0" x="211" y="310"><field name="directionType">MoveRight</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="~I?mB~jU9vkYORO!G03;"><field name="NUM">1</field></shadow></value></block><block type="motion_speed_distance" id="PXQ_C#G1Cn?/9.[Ps?{]" x="106" y="413"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="JfcFR`Jz:==N_b`$37h$"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="t^@y4Smm1:/^1+85aR{0"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="P~^yLYy:2OI}nhW`Y`?["><field name="NUM">1</field></shadow></value></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_distance" id="wM^D9e?KxRA]I5|7+W{|"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="FB9[f)`]{j1[[QfG5b_Z"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="y7PxBIKHrV1+HWE_p+;0"><field name="directionType">MoveRight</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="~I?mB~jU9vkYORO!G03;"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="PXQ_C#G1Cn?/9.[Ps?{]"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="JfcFR`Jz:==N_b`$37h$"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="t^@y4Smm1:/^1+85aR{0"><field name="directionType">MoveLeft</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="P~^yLYy:2OI}nhW`Y`?["><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_distance', name: ['speedType', 'CUSTOM_MATH_NUM'] }
            ]
        },
        'fourFeet': {// 四足
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_distance" id="wM^D9e?KxRA]I5|7+W{|"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="FB9[f)`]{j1[[QfG5b_Z"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="}DbxZI6rH/ArtD#IuNe4"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="2spCoAr=TDcC62T.MSPj"><field name="NUM">1</field></shadow></value></block></next></block></next></block><block type="motion_speed_distance" id="y7PxBIKHrV1+HWE_p+;0" x="211" y="310"><field name="directionType">MoveRight</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="~I?mB~jU9vkYORO!G03;"><field name="NUM">1</field></shadow></value></block><block type="motion_speed_distance" id="PXQ_C#G1Cn?/9.[Ps?{]" x="106" y="413"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="JfcFR`Jz:==N_b`$37h$"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="t^@y4Smm1:/^1+85aR{0"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="P~^yLYy:2OI}nhW`Y`?["><field name="NUM">1</field></shadow></value></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_distance" id="wM^D9e?KxRA]I5|7+W{|"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="FB9[f)`]{j1[[QfG5b_Z"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="}DbxZI6rH/ArtD#IuNe4"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="2spCoAr=TDcC62T.MSPj"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="y7PxBIKHrV1+HWE_p+;0"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="~I?mB~jU9vkYORO!G03;"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="PXQ_C#G1Cn?/9.[Ps?{]"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="JfcFR`Jz:==N_b`$37h$"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_distance', name: ['speedType', 'CUSTOM_MATH_NUM'] }
            ]
        },
    },
    missionStandardTime:15*1000//通过任务的标准时间,单位毫秒
};