var courseData = {
    level: 1,
    stage: 3,
    knowledgePoint: 1,
    mission: 5,
    taskTitle: MSG['l1_s3_m5_' + window.moveType + '_title'] || MSG['l1_s3_m5_commonType_title'],
    helpList: {
        'commonType': [
            {
                'text': 'l1_help_007',
            }
        ],
    },    
    toolConfig: {
        'motion': ['motion_speed_continued_second', 'motion_speed_distance'],
        'acousto_optic': ['acoustooptic_paly_tone', 'acoustooptic_lights_on'],
    },
    program: {
        'commonType': {// 普通类别
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="73" y="174"><field name="PROGRAM_BRANCH">1</field><next><block type="acoustooptic_lights_on" id="E+7;RIP5*`ie^pVx^JUF"><field name="acoustoColor">#FF0000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="d60Ug6q`W{wyP^D1-iul"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="HIp9)v89@foSfo(wLsWM"><field name="acoustoColor">#FF0000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="Z!5hj9+PO22|1x+YMeIi"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="s#MP7)^g#:YWMGfmf)9S"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="f.mmK([skIV6!O3/+nwC"><field name="TIME">1</field></shadow></value></block></next></block></next></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="acoustooptic_lights_on" id="E+7;RIP5*`ie^pVx^JUF"><field name="acoustoColor">#FF0000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="d60Ug6q`W{wyP^D1-iul"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="HIp9)v89@foSfo(wLsWM"><field name="acoustoColor">#000000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="Z!5hj9+PO22|1x+YMeIi"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="s#MP7)^g#:YWMGfmf)9S"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_fast</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="f.mmK([skIV6!O3/+nwC"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="YM@w{9`S$la6;w{H%]d_"><field name="acoustoColor">#FF0000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="IF;2+Hd@]@I~XBrEeh47"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="|)EVF6BXLV09o]GT,Xr2"><field name="acoustoColor">#000000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="R,Q06KF!i}-:jhY75)sk"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="z-,hRuMFt9xs7q^y{0J;"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_fast</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="A^FJ=EeVdJ+8?/GPk=NA"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="!Ie}sZ_feFl;x3Q?RXte"><field name="acoustoColor">#FF0000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="QO@L[D?y7EUxG[({tH2z"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="Q}f$+z])E0~z{7CRuRL-"><field name="acoustoColor">#000000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="(]gPNGXLN^T=RD35,T@c"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="1[W4/itpW:O%O$~@FA2o"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_fast</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="{R4dySpSO6FZEt0s$vpM"><field name="TIME">1</field></shadow></value></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>',
            ignore: [
                { index: 0,type: 'motion_speed_continued_second', name: ['MOTION_SPEED_CONTINUED_SECOND'] },
                { index: 1,type: 'motion_speed_continued_second', name: ['MOTION_SPEED_CONTINUED_SECOND'] },
                { index: 2,type: 'motion_speed_continued_second', name: ['MOTION_SPEED_CONTINUED_SECOND'] }
            ]
        },
        'doubleFeet': {// 双足
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="82" y="180"><field name="PROGRAM_BRANCH">1</field><next><block type="acoustooptic_lights_on" id="PMq()cs3E$v7j{z2pLl)"><field name="acoustoColor">#FF0000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="V]raWb!K-up@e}.Jj,MG"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="e;^h]YZc3]5/-dTD5F_3"><field name="acoustoColor">#FF0000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="T,cl(J_@lAz[uVIFe;=`"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_distance" id="JmpuiPACHb;~RBVsP-7."><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="m0`87xt.[sSj,aHZnKbC"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="acoustooptic_lights_on" id="PMq()cs3E$v7j{z2pLl)"><field name="acoustoColor">#FF0000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="V]raWb!K-up@e}.Jj,MG"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="e;^h]YZc3]5/-dTD5F_3"><field name="acoustoColor">#000000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="T,cl(J_@lAz[uVIFe;=`"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_distance" id="JmpuiPACHb;~RBVsP-7."><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_fast</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="m0`87xt.[sSj,aHZnKbC"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="UjDp5SKC|6A$qaH^E[xK"><field name="acoustoColor">#FF0000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="$Z139YVa4Ooo~A2e/DMh"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="D,-LlkJ3B|M4OLvFb#w7"><field name="acoustoColor">#000000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="+TfjvqUt%rAR%-%hId!0"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_distance" id="d^|j|0Q!tiV$clj|r5`]"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_fast</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="d6p_D#BZlbQ4:9vi;~N;"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="#JArT4C]|N3Lp~*dbJ:_"><field name="acoustoColor">#FF0000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="/eLn=Ro155T,et%b=^YC"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_lights_on" id="AV:Kn~=san]Gd)1W72Ee"><field name="acoustoColor">#000000</field><value name="ACOUSTOOPTIC_LIGHTS_ON"><shadow type="acoustooptic_custom_math_num" id="b9e|TH7EeciK=k!LORH5"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_distance" id="1%xoIDgA*cw=|Capj`pc"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_fast</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="5(1ED:VO96[x)y}g]_J("><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>',
            ignore: [
                { index: 0, type: 'motion_speed_distance', name: ['CUSTOM_MATH_NUM'] },
                { index: 1, type: 'motion_speed_distance', name: ['CUSTOM_MATH_NUM'] },
                { index: 2, type: 'motion_speed_distance', name: ['CUSTOM_MATH_NUM'] }
            ]
        },
    },
    missionStandardTime:20*1000//通过任务的标准时间,单位毫秒
};