var courseData = {
    level: 1,
    stage: 7,
    knowledgePoint: 1,
    mission: 8,
    taskTitle: MSG['l1_s7_m8_' + window.moveType + '_title'] || MSG['l1_s7_m8_commonType_title'],
    toolConfig: {
        'motion': ['motion_speed_continued_second', 'motion_speed_distance'],
        'control': ['custom_control_wait_seconds', 'custom_control_repeat_times', 'custom_control_if_else'],
        'acousto_optic': ['acoustooptic_paly_tone', 'acoustooptic_lights_on'],
        'sensors': ['sensor_phone_pad_tilt'],
    },
    program: {
        'commonType': {// 普通类别
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="156"><field name="PROGRAM_BRANCH">1</field><next><block type="custom_control_do_while" id="Ovkr.:M$(day:TNO/gF9"><statement name="DO"><block type="acoustooptic_paly_tone" id="%Ew9wkOK^;c%o%5.3cBS"><field name="toneName">C5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="GNC.8dBNF$*wY5H/:w[0"><field name="toneName">D5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="#Z~}g|V{6VuN|{OaBKa$"><field name="toneName">E5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="No]Us]Dv?_Wf}_ct*YV@"><field name="toneName">C5</field><field name="beatType">beat_4_1</field></block></next></block></next></block></next></block></statement><value name="BOOL"><block type="sensor_phone_pad_tilt" id="vc4_/59PAON=tSbz:n5}"><field name="TILT_TYPE">tilt_left</field></block></value><next><block type="custom_control_wait_seconds" id="5p)vB`/dqb@:A`A+:.k:"><value name="CUSTOM_CONTROL_WAIT_SECONDS"><shadow type="custom_math_num" id="1VB;8@F,wNy0J*7T2)W."><field name="NUM">0.5</field></shadow></value><next><block type="motion_speed_continued_second" id="V*%$20w@0)0F[;L3zhHR"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id=";{I[l2i#B?}h0K,kn!yZ"><field name="TIME">1</field></shadow></value></block></next></block></next></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="70"><field name="PROGRAM_BRANCH">1</field><next><block type="custom_control_do_while" id="Ovkr.:M$(day:TNO/gF9"><statement name="DO"><block type="acoustooptic_paly_tone" id="%Ew9wkOK^;c%o%5.3cBS"><field name="toneName">C5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="GNC.8dBNF$*wY5H/:w[0"><field name="toneName">D5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="#Z~}g|V{6VuN|{OaBKa$"><field name="toneName">E5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="No]Us]Dv?_Wf}_ct*YV@"><field name="toneName">C5</field><field name="beatType">beat_4_1</field></block></next></block></next></block></next></block></statement><value name="BOOL"><block type="sensor_phone_pad_tilt" id="vc4_/59PAON=tSbz:n5}"><field name="TILT_TYPE">tilt_left</field></block></value><next><block type="custom_control_wait_seconds" id="5p)vB`/dqb@:A`A+:.k:"><value name="CUSTOM_CONTROL_WAIT_SECONDS"><shadow type="custom_math_num" id="1VB;8@F,wNy0J*7T2)W."><field name="NUM">0.5</field></shadow></value><next><block type="motion_speed_continued_second" id="V*%$20w@0)0F[;L3zhHR"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id=";{I[l2i#B?}h0K,kn!yZ"><field name="TIME">1</field></shadow></value></block></next></block></next></block></next></block></xml>',
            ignore: [
                { type: 'acoustooptic_lights_on', name: ['ACOUSTOOPTIC_LIGHTS_ON'] },
                { type: 'motion_speed_continued_second', name: ['speedType', 'MOTION_SPEED_CONTINUED_SECOND'] }
            ]
        },
        'doubleFeet': {// 双足
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="156"><field name="PROGRAM_BRANCH">1</field><next><block type="custom_control_do_while" id="Ovkr.:M$(day:TNO/gF9"><statement name="DO"><block type="acoustooptic_paly_tone" id="%Ew9wkOK^;c%o%5.3cBS"><field name="toneName">C5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="GNC.8dBNF$*wY5H/:w[0"><field name="toneName">D5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="#Z~}g|V{6VuN|{OaBKa$"><field name="toneName">E5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="No]Us]Dv?_Wf}_ct*YV@"><field name="toneName">C5</field><field name="beatType">beat_4_1</field></block></next></block></next></block></next></block></statement><value name="BOOL"><block type="sensor_phone_pad_tilt" id="vc4_/59PAON=tSbz:n5}"><field name="TILT_TYPE">tilt_left</field></block></value><next><block type="custom_control_wait_seconds" id="5p)vB`/dqb@:A`A+:.k:"><value name="CUSTOM_CONTROL_WAIT_SECONDS"><shadow type="custom_math_num" id="1VB;8@F,wNy0J*7T2)W."><field name="NUM">0.5</field></shadow></value><next><block type="motion_speed_distance" id="7/bs1}+PL_4b?B^m[mf8"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id=")[j}Y8Ei#t/WME/]WH-C"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="156"><field name="PROGRAM_BRANCH">1</field><next><block type="custom_control_do_while" id="Ovkr.:M$(day:TNO/gF9"><statement name="DO"><block type="acoustooptic_paly_tone" id="%Ew9wkOK^;c%o%5.3cBS"><field name="toneName">C5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="GNC.8dBNF$*wY5H/:w[0"><field name="toneName">D5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="#Z~}g|V{6VuN|{OaBKa$"><field name="toneName">E5</field><field name="beatType">beat_4_1</field><next><block type="acoustooptic_paly_tone" id="No]Us]Dv?_Wf}_ct*YV@"><field name="toneName">C5</field><field name="beatType">beat_4_1</field></block></next></block></next></block></next></block></statement><value name="BOOL"><block type="sensor_phone_pad_tilt" id="vc4_/59PAON=tSbz:n5}"><field name="TILT_TYPE">tilt_left</field></block></value><next><block type="custom_control_wait_seconds" id="5p)vB`/dqb@:A`A+:.k:"><value name="CUSTOM_CONTROL_WAIT_SECONDS"><shadow type="custom_math_num" id="1VB;8@F,wNy0J*7T2)W."><field name="NUM">0.5</field></shadow></value><next><block type="motion_speed_distance" id="7/bs1}+PL_4b?B^m[mf8"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id=")[j}Y8Ei#t/WME/]WH-C"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></xml>',
            ignore: [
                { type: 'acoustooptic_lights_on', name: ['ACOUSTOOPTIC_LIGHTS_ON'] },
                { type: 'motion_speed_distance', name: ['speedType', 'CUSTOM_MATH_NUM'] }
            ]
        },
    },
    missionStandardTime:30*1000//通过任务的标准时间,单位毫秒
};