var courseData = {
    level: 1,
    stage: 2,
    knowledgePoint: 1,
    mission: 9,
    taskTitle: MSG['l1_s2_m9_' + window.moveType + '_title'] || MSG['l1_s2_m9_commonType_title'],
    helpList: {
        'commonType': [
            {
                'text': 'l1_help_015',
            }, {
                'text': 'l1_help_016',
            }, {
                'text': 'l1_help_008',
            }
        ],
    },    
    toolConfig: {
        'motion': ['motion_speed_continued_second', 'motion_speed_distance'],
        'acousto_optic': ['acoustooptic_paly_tone', 'acoustooptic_paly_sound'],
    },
    program: {
        'commonType': {// 普通类别
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="45" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="acoustooptic_paly_sound" id="h0giFh)I8Y`uZ9gk{CVN"><field name="isDelay">true</field><field name="chooseSound">emotion:surprise</field><next><block type="motion_speed_continued_second" id="YKs(pi~5*qYeZS)~dew$"><field name="directionType">TurnLeft</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="k2Q?wUsN8HJ@SFOoD,^K"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="~DN#)!.Q=mn|NY#_Zn=["><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="pK^nvyF7[Vye^));?vXW"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="W+q8ySwcGEUO:]|Y{qND"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="fT@drbq$AFd=bu2@nO$G"><field name="TIME">1</field></shadow></value></block></next></block></next></block></next></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="45" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="acoustooptic_paly_sound" id="h0giFh)I8Y`uZ9gk{CVN"><field name="isDelay">true</field><field name="chooseSound">emotion:actingcute</field><next><block type="motion_speed_continued_second" id="~DN#)!.Q=mn|NY#_Zn=["><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="pK^nvyF7[Vye^));?vXW"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="W+q8ySwcGEUO:]|Y{qND"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="fT@drbq$AFd=bu2@nO$G"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="bfzL~kiF|1utg!Cx;BSg"><field name="isDelay">true</field><field name="chooseSound">emotion:actingcute</field><next><block type="motion_speed_continued_second" id="t=3q!#w:oV.=Gkk]A7E,"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="^ocK6,Hbr?J?14Z#TuMK"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="1IQHd:4H,B%P1j!nyOd2"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id=")35j268W-A[@juEP`l69"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="yV_WGV4ZXEfLj#vF7+]Q"><field name="isDelay">true</field><field name="chooseSound">emotion:actingcute</field><next><block type="motion_speed_continued_second" id="ILz*uAsk|Mx}75E+!kpt"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="V7Is~x1}Ocg7tRt30kid"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="n-DWN%1_Eko)P`C=t_i`"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="h|hnWxbZ!#AI,ChOg?VX"><field name="TIME">1</field></shadow></value></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_continued_second', name: ['speedType','MOTION_SPEED_CONTINUED_SECOND'] },
                { type: 'motion_speed_continued_second', name: ['speedType', 'MOTION_SPEED_CONTINUED_SECOND'] }
            ],
        },
        'doubleFeet': {// 双足
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="acoustooptic_paly_sound" id="7n*^SOukP.5u_dP#x82y"><field name="isDelay">true</field><field name="chooseSound">emotion:surprise</field><next><block type="motion_speed_distance" id="P^gr|DsaA{vsF$|bBX:="><field name="directionType">MoveLeft</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="MFT15W!oSGH9h}mtNeA|"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="bRfJ];t8lu9;3vN^z~et"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="wD3k.30yel.kCfUr#pH*"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="wtn|L]_BtLZJB5ENSr;/"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="E);U:`J)s8:MkEp9l1?]"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="acoustooptic_paly_sound" id="7n*^SOukP.5u_dP#x82y"><field name="isDelay">true</field><field name="chooseSound">emotion:actingcute</field><next><block type="motion_speed_distance" id="P^gr|DsaA{vsF$|bBX:="><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="MFT15W!oSGH9h}mtNeA|"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="bRfJ];t8lu9;3vN^z~et"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="wD3k.30yel.kCfUr#pH*"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="J^,N%6f8EYUl08+.?|sh"><field name="isDelay">true</field><field name="chooseSound">emotion:actingcute</field><next><block type="motion_speed_distance" id="I.+Zr}[;f07^)bWkF{r/"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="oqUccm[Bk(99s~9nO~~;"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="8GJ(HFnOTR9Gs`*z4^Ot"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="n({pxsy{%7,(#}8GG$f4"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="IDyPv_`4Pno^6h,XJsR;"><field name="isDelay">true</field><field name="chooseSound">emotion:actingcute</field><next><block type="motion_speed_distance" id="^eOmKk;/S3:?dbe~I9H="><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id=")%0JQc9_|U];jy;C@jIk"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="W]rVVfwZ[p1X+xsWa^R,"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="vW0;Em}W5%xSvx7+$Mt/"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_distance', name: ['speedType', 'DISTANCE'] },
                { type: 'motion_speed_distance', name: ['speedType', 'DISTANCE'] }
            ],
        },
        'fourFeet': {// 四足
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="acoustooptic_paly_sound" id="7n*^SOukP.5u_dP#x82y"><field name="isDelay">true</field><field name="chooseSound">emotion:surprise</field><next><block type="motion_speed_distance" id="P^gr|DsaA{vsF$|bBX:="><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="MFT15W!oSGH9h}mtNeA|"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="bRfJ];t8lu9;3vN^z~et"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="wD3k.30yel.kCfUr#pH*"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="wtn|L]_BtLZJB5ENSr;/"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="E);U:`J)s8:MkEp9l1?]"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="acoustooptic_paly_sound" id="7n*^SOukP.5u_dP#x82y"><field name="isDelay">true</field><field name="chooseSound">emotion:actingcute</field><next><block type="motion_speed_distance" id="P^gr|DsaA{vsF$|bBX:="><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="MFT15W!oSGH9h}mtNeA|"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="bRfJ];t8lu9;3vN^z~et"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="wD3k.30yel.kCfUr#pH*"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="J^,N%6f8EYUl08+.?|sh"><field name="isDelay">true</field><field name="chooseSound">emotion:actingcute</field><next><block type="motion_speed_distance" id="I.+Zr}[;f07^)bWkF{r/"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="oqUccm[Bk(99s~9nO~~;"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="8GJ(HFnOTR9Gs`*z4^Ot"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="n({pxsy{%7,(#}8GG$f4"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="IDyPv_`4Pno^6h,XJsR;"><field name="isDelay">true</field><field name="chooseSound">emotion:actingcute</field><next><block type="motion_speed_distance" id="^eOmKk;/S3:?dbe~I9H="><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id=")%0JQc9_|U];jy;C@jIk"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="W]rVVfwZ[p1X+xsWa^R,"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="vW0;Em}W5%xSvx7+$Mt/"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_distance', name: ['speedType', 'DISTANCE'] },
                { type: 'motion_speed_distance', name: ['speedType', 'DISTANCE'] }
            ],
        },
        
    },
    missionStandardTime:15*1000//通过任务的标准时间,单位毫秒
};