var courseData = {
    level: 1,
    stage: 2,
    knowledgePoint: 1,
    mission: 7,
    taskTitle: MSG['l1_s2_m7_' + window.moveType + '_title'] || MSG['l1_s2_m7_commonType_title'],
    helpList: {
        'commonType': [
            {
                'text': 'l1_help_007',
            },
            {
                'text': 'l1_help_008',
            }
        ],
    },    
    toolConfig: {
        'motion': ['motion_speed_continued_second', 'motion_speed_distance'],
        'acousto_optic': ['acoustooptic_paly_tone'],
    },
    program: {
        'commonType': {// 普通类别
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_continued_second" id="W0e2K2Qb.x80?]i0i7CT"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="%4P/9,R+BPlB0WcLPoN7"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="]]Q^5gu/1y4eG:KJPvgB"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_continued_second" id="vWo@6_-;!{JHb_~n-j[o"><field name="directionType">TurnRight</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="v}:Jf#{+^(l=nXenCxqX"><field name="TIME">1</field></shadow></value></block></next></block></next></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_continued_second" id="W0e2K2Qb.x80?]i0i7CT"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="%4P/9,R+BPlB0WcLPoN7"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="]]Q^5gu/1y4eG:KJPvgB"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_continued_second" id="vWo@6_-;!{JHb_~n-j[o"><field name="directionType">TurnRight</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="v}:Jf#{+^(l=nXenCxqX"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="@:;a%-axwOB:+9^S-/H:"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="R.ivE0mT{:U6xM^-7,#B"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="f/pQt?(iCi|/nFiQ9bex"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_continued_second" id="m)y_viLj?%Drom!h%7#E"><field name="directionType">TurnRight</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="hxl4_K;~pg8`|/6J,cwl"><field name="TIME">1</field></shadow></value><next><block type="motion_speed_continued_second" id="QV3TL56*w{#(+KU%4)tG"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="agOoa?d7hn%59rE(+6]u"><field name="TIME">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="oIocd}r:{lt)+,,}jII2"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_continued_second" id="-Dn#PNzg(}o=EU=_0S,U"><field name="directionType">TurnRight</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="|hX/iPo~p9#vk0DdV`{1"><field name="TIME">1</field></shadow></value></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_continued_second', name: ['speedType', 'MOTION_SPEED_CONTINUED_SECOND'] }
            ]
        },
        'doubleFeet': {// 双足
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_distance" id="%W7v@ew)$5W,U9(C*r;y"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id=":,x8A1n8IR,f{KIVKSwX"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="GyPx~/|RY(7a@-!}9nu7"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_distance" id="IU7udY@CqI(/m=kLSrLZ"><field name="directionType">MoveRight</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="q^f?y2KRuX=pxA-nBm~A"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="115"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_distance" id="%W7v@ew)$5W,U9(C*r;y"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id=":,x8A1n8IR,f{KIVKSwX"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="GyPx~/|RY(7a@-!}9nu7"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_distance" id="IU7udY@CqI(/m=kLSrLZ"><field name="directionType">MoveRight</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="q^f?y2KRuX=pxA-nBm~A"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="#eq`:s!}So1l,aW4_-ZD"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="aSW_oyy5}19qvIUZsrx6"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="Zn|HN,,4nry91L.XyM%K"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_distance" id="sQF!j|%L-.prl*NBZ(V/"><field name="directionType">MoveRight</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="2R|,C2HLqaCHS,!-re0d"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="@6{Bw4e|yG3AkUWW9[*R"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="Nxgkc;lq%3wBXv#i,^A!"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="~4S]Agm{yL!MVJarKgkj"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_distance" id="Gv+BdAu|/J8L:=E:E=c3"><field name="directionType">MoveRight</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="[9}5v%M1K+{iqH9fO[Jf"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_distance', name: ['speedType', 'CUSTOM_MATH_NUM'] }
            ]
        },
        'fourFeet': {// 四足
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="93"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_distance" id="%W7v@ew)$5W,U9(C*r;y"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id=":,x8A1n8IR,f{KIVKSwX"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="GyPx~/|RY(7a@-!}9nu7"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_distance" id="IU7udY@CqI(/m=kLSrLZ"><field name="directionType">MoveRight</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="q^f?y2KRuX=pxA-nBm~A"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="115"><field name="PROGRAM_BRANCH">1</field><next><block type="motion_speed_distance" id="%W7v@ew)$5W,U9(C*r;y"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id=":,x8A1n8IR,f{KIVKSwX"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="GyPx~/|RY(7a@-!}9nu7"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_distance" id="IU7udY@CqI(/m=kLSrLZ"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="q^f?y2KRuX=pxA-nBm~A"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="W$:3@,3fFmR3_;THxLgz"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="FvX=pyIK1YS)-(JOdy_d"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="$C)XuiKjrsgm`nr0+l#M"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_distance" id="09V9.FdP-k[fx0Nw14nE"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="0seb=tG1+inlL^De{Wvp"><field name="NUM">1</field></shadow></value><next><block type="motion_speed_distance" id="t0t~(imc~eYYMPoT?%F}"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="Q#ZESB-=lL8Q=d/=e%kc"><field name="NUM">1</field></shadow></value><next><block type="acoustooptic_paly_sound" id="^|3ZE[S[cl3GHXr)R+b3"><field name="isDelay">true</field><field name="chooseSound">emotion:happy</field><next><block type="motion_speed_distance" id="52=,-2XcsT)9Sg$@T${H"><field name="directionType">MoveBackward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="5/5^;wiXOTk_#i4mZTFn"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_distance', name: ['speedType', 'CUSTOM_MATH_NUM'] }
            ]
        },
       
    },
    missionStandardTime:15*1000//通过任务的标准时间,单位毫秒
};