var courseData = {
    level: 1,
    stage: 10,
    knowledgePoint: 1,
    mission: 6,
    taskTitle: MSG['l1_s10_m6_' + window.moveType + '_title'] || MSG['l1_s10_m6_commonType_title'],
    toolConfig: {
        'motion': ['motion_action_speed', 'motion_action_stop', 'motion_speed_continued_second', 'motion_speed_distance'],
        'acousto_optic': ['acoustooptic_paly_tone', 'acoustooptic_lights_on'],
        'control': ['custom_control_infinite_loop', 'custom_control_if_else', 'custom_control_wait_for'],
        'sensors': ['sensor_obstacle_distance'],
        'math': ['custom_math_add_minus','custom_math_logic_compare']
    },
    helpList: {
        'commonType': [
            {
                'text': 'l1_help_033',
            }
        ],
    },
    guideClick: ['#\\:6'],
    program: {
        'commonType': {// 普通类别
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="156"><field name="PROGRAM_BRANCH">1</field><next><block type="custom_control_repeat_times" id="K$5!)z(;KMW%BmmFXT~_"><value name="CUSTOM_CONTROL_REPEAT_TIMES"><shadow type="custom_math_num" id="h8!hZ*$;nu0+)vg%|xmc"><field name="NUM">3</field></shadow></value><statement name="CUSTOM_CONTROL_DO0"><block type="custom_control_wait_for" id="(VqDv~5xbSxPf{-Y{43z"><value name="CUSTOM_CONTROL_WAIT_FOR"><block type="custom_math_logic_compare" id=",cd+2cEW/ad23~mAJe!@"><field name="LOGIC_COMPARE">&lt;</field><value name="A"><shadow type="custom_math_num" id="0Q9rzo10{4@VjquJ5tPM"><field name="NUM">1</field></shadow><block type="sensor_obstacle_distance" id="9-phn,LZtcS:ZqX+-iWo"></block></value><value name="B"><shadow type="custom_math_num" id="`-|bnv;|)$tFwTczw$;H"><field name="NUM">5</field></shadow></value></block></value><next><block type="motion_speed_continued_second" id="sBzl/2.xqXJra6x=QYf|"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="/YA4BQW^T$]dT#=`f`W+"><field name="TIME">1</field></shadow></value></block></next></block></statement></block></next></block><block type="sensor_obstacle_distance" id="P_8k3e,;aJdQ{I,{TI`;" x="201" y="435"></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="156"><field name="PROGRAM_BRANCH">1</field><next><block type="custom_control_repeat_times" id="K$5!)z(;KMW%BmmFXT~_"><value name="CUSTOM_CONTROL_REPEAT_TIMES"><shadow type="custom_math_num" id="h8!hZ*$;nu0+)vg%|xmc"><field name="NUM">3</field></shadow></value><statement name="CUSTOM_CONTROL_DO0"><block type="custom_control_wait_for" id="(VqDv~5xbSxPf{-Y{43z"><value name="CUSTOM_CONTROL_WAIT_FOR"><block type="custom_math_logic_compare" id=",cd+2cEW/ad23~mAJe!@"><field name="LOGIC_COMPARE">&lt;</field><value name="A"><shadow type="custom_math_num" id="0Q9rzo10{4@VjquJ5tPM"><field name="NUM">1</field></shadow><block type="sensor_obstacle_distance" id="9-phn,LZtcS:ZqX+-iWo"></block></value><value name="B"><shadow type="custom_math_num" id="`-|bnv;|)$tFwTczw$;H"><field name="NUM">5</field></shadow></value></block></value><next><block type="motion_speed_continued_second" id="sBzl/2.xqXJra6x=QYf|"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="MOTION_SPEED_CONTINUED_SECOND"><shadow type="motion_custom_math_num" id="/YA4BQW^T$]dT#=`f`W+"><field name="TIME">1</field></shadow><block type="custom_math_add_minus" id="0[Z[H~r*m^6/^Xj}9:^u"><field name="OPERATOR">÷</field><value name="FIRST_EXPRESSION"><shadow type="custom_math_num" id="T)nGZizt7OX.mP1r68Yr"><field name="NUM">1</field></shadow><block type="sensor_obstacle_distance" id="P_8k3e,;aJdQ{I,{TI`;"></block></value><value name="SECOND_EXPRESSION"><shadow type="custom_math_num" id="fOCrk4_Mm(MSbVsoLVSf"><field name="NUM">4</field></shadow></value></block></value></block></next></block></statement></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_continued_second', name: ['speedType'] },
            ]
        },
        'doubleFeet': {// 双足
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="156"><field name="PROGRAM_BRANCH">1</field><next><block type="custom_control_repeat_times" id="K$5!)z(;KMW%BmmFXT~_"><value name="CUSTOM_CONTROL_REPEAT_TIMES"><shadow type="custom_math_num" id="h8!hZ*$;nu0+)vg%|xmc"><field name="NUM">3</field></shadow></value><statement name="CUSTOM_CONTROL_DO0"><block type="custom_control_wait_for" id="(VqDv~5xbSxPf{-Y{43z"><value name="CUSTOM_CONTROL_WAIT_FOR"><block type="custom_math_logic_compare" id=",cd+2cEW/ad23~mAJe!@"><field name="LOGIC_COMPARE">&lt;</field><value name="A"><shadow type="custom_math_num" id="0Q9rzo10{4@VjquJ5tPM"><field name="NUM">1</field></shadow><block type="sensor_obstacle_distance" id="9-phn,LZtcS:ZqX+-iWo"></block></value><value name="B"><shadow type="custom_math_num" id="`-|bnv;|)$tFwTczw$;H"><field name="NUM">5</field></shadow></value></block></value><next><block type="motion_speed_distance" id=")Rve0k[LG{Pp7fXvUN`H"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="(a:^?NhT7^o9P*)+kz4p"><field name="NUM">2</field></shadow></value></block></next></block></statement></block></next></block><block type="sensor_obstacle_distance" id="P_8k3e,;aJdQ{I,{TI`;" x="201" y="435"></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="156"><field name="PROGRAM_BRANCH">1</field><next><block type="custom_control_repeat_times" id="K$5!)z(;KMW%BmmFXT~_"><value name="CUSTOM_CONTROL_REPEAT_TIMES"><shadow type="custom_math_num" id="h8!hZ*$;nu0+)vg%|xmc"><field name="NUM">3</field></shadow></value><statement name="CUSTOM_CONTROL_DO0"><block type="custom_control_wait_for" id="(VqDv~5xbSxPf{-Y{43z"><value name="CUSTOM_CONTROL_WAIT_FOR"><block type="custom_math_logic_compare" id=",cd+2cEW/ad23~mAJe!@"><field name="LOGIC_COMPARE">&lt;</field><value name="A"><shadow type="custom_math_num" id="0Q9rzo10{4@VjquJ5tPM"><field name="NUM">1</field></shadow><block type="sensor_obstacle_distance" id="9-phn,LZtcS:ZqX+-iWo"></block></value><value name="B"><shadow type="custom_math_num" id="`-|bnv;|)$tFwTczw$;H"><field name="NUM">5</field></shadow></value></block></value><next><block type="motion_speed_distance" id=")Rve0k[LG{Pp7fXvUN`H"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="(a:^?NhT7^o9P*)+kz4p"><field name="NUM">2</field></shadow><block type="custom_math_add_minus" id="MLLf!OYnl[1qaMM!gtvj"><field name="OPERATOR">÷</field><value name="FIRST_EXPRESSION"><shadow type="custom_math_num" id="Tp-^UBB[BA_?ZC!)2~If"><field name="NUM">1</field></shadow><block type="sensor_obstacle_distance" id="P_8k3e,;aJdQ{I,{TI`;"></block></value><value name="SECOND_EXPRESSION"><shadow type="custom_math_num" id="S/hO/(OS2b4$6)fzPw+x"><field name="NUM">4</field></shadow></value></block></value></block></next></block></statement></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_distance', name: ['speedType'] },
            ]
        },
        'fourFeet': {// 四足
            init: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="156"><field name="PROGRAM_BRANCH">1</field><next><block type="custom_control_repeat_times" id="K$5!)z(;KMW%BmmFXT~_"><value name="CUSTOM_CONTROL_REPEAT_TIMES"><shadow type="custom_math_num" id="h8!hZ*$;nu0+)vg%|xmc"><field name="NUM">3</field></shadow></value><statement name="CUSTOM_CONTROL_DO0"><block type="custom_control_wait_for" id="(VqDv~5xbSxPf{-Y{43z"><value name="CUSTOM_CONTROL_WAIT_FOR"><block type="custom_math_logic_compare" id=",cd+2cEW/ad23~mAJe!@"><field name="LOGIC_COMPARE">&lt;</field><value name="A"><shadow type="custom_math_num" id="0Q9rzo10{4@VjquJ5tPM"><field name="NUM">1</field></shadow><block type="sensor_obstacle_distance" id="9-phn,LZtcS:ZqX+-iWo"></block></value><value name="B"><shadow type="custom_math_num" id="`-|bnv;|)$tFwTczw$;H"><field name="NUM">5</field></shadow></value></block></value><next><block type="motion_speed_distance" id=")Rve0k[LG{Pp7fXvUN`H"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="(a:^?NhT7^o9P*)+kz4p"><field name="NUM">2</field></shadow></value></block></next></block></statement></block></next></block><block type="sensor_obstacle_distance" id="P_8k3e,;aJdQ{I,{TI`;" x="201" y="435"></block></xml>',
            standard: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="program_start" id="RBpqO=zS:Min@~s1YZVV" deletable="false" x="50" y="156"><field name="PROGRAM_BRANCH">1</field><next><block type="custom_control_repeat_times" id="K$5!)z(;KMW%BmmFXT~_"><value name="CUSTOM_CONTROL_REPEAT_TIMES"><shadow type="custom_math_num" id="h8!hZ*$;nu0+)vg%|xmc"><field name="NUM">3</field></shadow></value><statement name="CUSTOM_CONTROL_DO0"><block type="custom_control_wait_for" id="(VqDv~5xbSxPf{-Y{43z"><value name="CUSTOM_CONTROL_WAIT_FOR"><block type="custom_math_logic_compare" id=",cd+2cEW/ad23~mAJe!@"><field name="LOGIC_COMPARE">&lt;</field><value name="A"><shadow type="custom_math_num" id="0Q9rzo10{4@VjquJ5tPM"><field name="NUM">1</field></shadow><block type="sensor_obstacle_distance" id="9-phn,LZtcS:ZqX+-iWo"></block></value><value name="B"><shadow type="custom_math_num" id="`-|bnv;|)$tFwTczw$;H"><field name="NUM">5</field></shadow></value></block></value><next><block type="motion_speed_distance" id=")Rve0k[LG{Pp7fXvUN`H"><field name="directionType">MoveForward</field><field name="speedType">id_motion_speed_normal</field><value name="CUSTOM_MATH_NUM"><shadow type="sys_custom_math_num" id="(a:^?NhT7^o9P*)+kz4p"><field name="NUM">2</field></shadow><block type="custom_math_add_minus" id="MLLf!OYnl[1qaMM!gtvj"><field name="OPERATOR">÷</field><value name="FIRST_EXPRESSION"><shadow type="custom_math_num" id="Tp-^UBB[BA_?ZC!)2~If"><field name="NUM">1</field></shadow><block type="sensor_obstacle_distance" id="P_8k3e,;aJdQ{I,{TI`;"></block></value><value name="SECOND_EXPRESSION"><shadow type="custom_math_num" id="S/hO/(OS2b4$6)fzPw+x"><field name="NUM">4</field></shadow></value></block></value></block></next></block></statement></block></next></block></xml>',
            ignore: [
                { type: 'motion_speed_distance', name: ['speedType'] },
            ]
        },
    },
    missionStandardTime:35*1000//通过任务的标准时间,单位毫秒
};